### ISSUE TITLE
how can set password for my users

### ISSUE THREAD

**Issue by mahmoodhojabri** [Nyr/openvpn-install#102]
hello, thanks for supporting and thanks for your good script. i'm beginner in ubuntu. i install your script, but script don't ask password for my client. how can set password and how can set expire date for users for example expire after 1 month and how can use tcp? thanks again.

**Comment by stefancrain** [comment]
Hi @mahmoodhojabri - Please look through the closed issues for answers to your questions before you post. This is now the **fourth** time passwords have been requested, they wont be added because they don't fit the intended use of this project. 
* Passwords were been addressed in #36, #40, #44, #97 I doubt this is any different. 
* Currently the script can revoke certificates manually, but if you're interested in automating check out  [these docs](https://openvpn.net/index.php/open-source/documentation/howto.html#revoke)

**Comment by stefancrain** [comment]
@mahmoodhojabri looking through the public fork of this project I found [this fork](https://github.com/drdada/openvpn-install) which has expiring password certificates. I've not tested, but it lists the features you're looking for. Best of luck.

**Comment by Nyr** [comment]
Thanks @stefancrain.

To use TCP, just change `proto udp` to `proto tcp` for both the client and server config files (or just edit the script before installing).
