### ISSUE TITLE
Default comments are not in the openvpn configuration for client or server

### ISSUE THREAD

**Issue by TheDoctorsLife** [Nyr/openvpn-install#126]
Is this on purpose? Theres certain settings I'd like to change (in the relation to security increases) and the lack of comments is annoying. Is there anyway to keep those without completely resetting the configuration of openvpn?

**Comment by Nyr** [comment]
Comments are not included since the configuration is pretty simple/barebones anyway.

If you want to modify parameters related to security, I would assume that you have deep knowledge of the OpenVPN manual anyway, which is the proper place to get documentation.

**TL;DR:** will not change this, sorry.

**Comment by TheDoctorsLife** [comment]
Alright, I do have a deep understanding, I was just curios as to why they weren't there, thanks.
