### ISSUE TITLE
Should use apt-get for easy-rsa?

### ISSUE THREAD

**Issue by knocte** [Nyr/openvpn-install#127]
Hey, just came from https://www.digitalocean.com/community/tutorials/how-to-set-up-an-openvpn-server-on-ubuntu-14-04 where this repo was recommended. Looks very useful indeed, but was wondering, why download the easy-rsa's tarball instead of installing the package via `apt-get`?

Thanks

**Comment by Nyr** [comment]
Because many distributions are packing older versions, others are including `easy-rsa` with the `openvpn` package... so it's less work for me to support the actual version than to support and test all of the possible variants (which are a lot).

Also, easy-rsa 3 uses more sane security choices that some older versions (2048 bit DH, `remote-cert-tls`, etc...).

**Comment by Angristan** [comment]
> Also, easy-rsa 3 uses more sane security choices that some older versions (2048 bit DH, remote-cert-tls, etc...).

Is it possible to use 4096 bits DH ?

**Comment by Nyr** [comment]
> Is it possible to use 4096 bits DH ?

Possible, yes.

Will I implement this change? No.

Long discussed topic, check other issues.

**Comment by Angristan** [comment]
I wasn't asking to implement it, I knew you wouldn't :)

I just want to know how to do it

**Comment by Nyr** [comment]
Many easy ways to do it, even without modifying the script. Check the easy-rsa [documentation](https://github.com/OpenVPN/easy-rsa/blob/master/doc/EasyRSA-Advanced.md#configuration-sources) for options.

The variable you want to deal with is `EASYRSA_KEY_SIZE`.

**Comment by Angristan** [comment]
Thanks !
