### ISSUE TITLE
Something breaks after system restart.

### ISSUE THREAD

**Issue by vpozniy** [Nyr/openvpn-install#140]
I'm a happy user of the script on Ubuntu Mate latest build, running it on Raspberry Pi 2. Everything goes smotth after installation, I'm able to generate the certs, copy them to my iPhone/iPad clients. Clients connect and can browse the internet and local net with no problem. Until I restart the system. I can still connect to the server after restart, but no traffic goes thru. Need help figuring out what causes the problem. 
 Here is my server.conf file:

```
port 1194
proto udp
dev tun
sndbuf 0
rcvbuf 0
ca ca.crt
cert server.crt
key server.key
dh dh.pem
topology subnet
server 10.8.0.0 255.255.255.0
ifconfig-pool-persist ipp.txt
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 192.168.0.101"
push "dhcp-option DNS 8.8.4.4"
keepalive 10 120
comp-lzo
persist-key
persist-tun
status openvpn-status.log
verb 3
crl-verify crl.pem

```

 dnsmasq running on boot on interface 192.168.0.101 ..
 any ideas?

**Comment by Nyr** [comment]
Sorry but this is an issue with your custom setup until proven otherwise. I can't really get why you push both the local cache and Google NS either, it's a bit weird. If you are caching responses from Google with dnsmasq, pushing `8.8.4.4` to the client seems counterintuitive.

I can't really debug every issue opened about things like this: check your firewall if any, check that dnsmasq is correctly forwarding to the recursor, check the routes, etc...

If it still doesn't work and you can't locate the issue, install on a clean image and then add the services you want like the DNS caching one by one until you locate the problem.
