### ISSUE TITLE
Bug in server.conf file when using OpenDNS (maybe others)

### ISSUE THREAD

**Issue by qahtani** [Nyr/openvpn-install#156]
I selected OpenDNS for my latest install and noticed that the lines:

push "dhcp-option DNS 208.67.222.222"
push "dhcp-option DNS 208.67.220.220"

Naturally, no DNS servers were getting pushed to clients.

**Comment by Nyr** [comment]
Sorry, I don't get what the issue is or why the DNS are not being pushed to clients?

Both lines are looking good to me.

**Comment by qahtani** [comment]
Sorry, I submitted without proofreading :(

I meant to say that those two lines were not put into the server.conf automatically.

Thanks for the work, by the way.

**Comment by Nyr** [comment]
I can't reproduce this issue and can't understand why it could happen, other than maybe you accidentally submitting 13 instead of 3.

By default the option 1 is selected and if you just press 3 and enter, you would actually submit 13, which is not defined.

This design could've been a bit more intuitive, I guess...
