### ISSUE TITLE
Unrevoke clients

### ISSUE THREAD

**Issue by DutchGameplayHQ** [Nyr/openvpn-install#157]
Will there ever be an option to unrevoke clients you have revoked?

Struggling a bit with this

**Comment by Nyr** [comment]
Certificate revocation shouldn't be reversed.

Just generate a new certificate.

**Comment by andre161292** [comment]
You can use the following script to unrevoke a certificate (taken from [this StackExchange post](https://superuser.com/a/1246952/140404) with some slight modification - give the guy an upvote!):

```bash
#!/bin/bash
set -e

keys_index_file="/etc/openvpn/server/easy-rsa/pki/index.txt"
linenumber="$(grep -n "/CN=$1" $keys_index_file | cut -f1 -d:)"
fileline="$(grep -n "/CN=$1" $keys_index_file)"
line="$(grep "/CN=$1" $keys_index_file)"

columns_number="$(echo $line | awk -F' ' '{print NF;}')"
echo $columns_number

if [[ $columns_number -eq 6 ]] && [[ $line == R* ]]; then

    column2="$(echo $fileline | awk '{print $2}')"
    column4="$(echo $fileline | awk '{print $4}')"
    column5="$(echo $fileline | awk '{print $5}')"
    column6="$(echo $fileline | awk '{print $6}')"
    echo -e "V\t$column2\t\t$column4\t$column5\t$column6" >> $keys_index_file
    sed -i "${linenumber}d" $keys_index_file

    cd /etc/openvpn/server/easy-rsa
    EASYRSA_CRL_DAYS=3650 ./easyrsa gen-crl
    rm -f /etc/openvpn/server/crl.pem
    cp /etc/openvpn/server/easy-rsa/pki/crl.pem /etc/openvpn/server/crl.pem
    # CRL is read with each client connection, when OpenVPN is dropped to nobody
    chown nobody:nogroup /etc/openvpn/server/crl.pem

    echo "Certificate unrevoked successfully."
    exit 0;

elif [[ $columns_number -eq 5 ]] && [[ $fileline == V* ]]; then

    echo "Certificate is already unrevoked and active"
    exit 0;

else

    echo "Error; Key index file may be corrupted."
    exit 1;

fi
```
Invoke it like this: `./revoke.sh username`

Make sure to backup the `/etc/openvpn/server` directory before executing.

**Comment by Martyn575** [comment]
I've got a remote system in the middle of nowhere. It communicates over 4G to our server. 4G is not cheap as i'm sure you can appreciate. There was a VPN screwup by me and it was sending all the traffic through to our vpn. It wasn't possible to get into teh system because it was so lagged up. To stop us getting bills for thousands of $ i had to revoke the vpn certificate. I had no other choice, i can't physically get into the system. 

Now here's the rub, at 4am last night, i worked out what the problem was, so now i want to unrevoke the certificate.

So the question is, why don't you add an option to unrevoke the certificate?
