### ISSUE TITLE
Not really an issue, but maybe you have an idea?

### ISSUE THREAD

**Issue by Yzord** [Nyr/openvpn-install#168]
I have setup 3 VPN servers with your script. I have to thank you for that!!

Now i want to cascading my connection with those 3 servers. So i connect to server one and my IP is changing to the one of server1. When i connect after that to server 2, it connects fine, but it does not change my IP to that of server 2. And when i connect to server 3 is does the same and log shows me that i try to connect from IP1.

Do you have any idea how to enable cascading?

**Comment by Nyr** [comment]
What are you trying to archieve with this? The "proper" way would be to connect each server to the next one and then you just connect to the first server.

This seems useless to me and would result in shitty performance, not sure why would you want to do it.

**Comment by Nyr** [comment]
Adding to that:

If your idea is to archieve some additional privacy, security or something like that, this is useless.

I've seen this setup with some commercial VPN providers and like your last issue: is just marketing bullshit with no benefits at all.

**Comment by Yzord** [comment]
Well, i hope you can't deny that it gives some extra privacy layers. If your exit IP is the IP of server 3 then the log refers to IP2 and so on. If you only have one VPN server, that log contains your home IP.

What i want to do is cascading my connection with multiple VPN servers

**Comment by Nyr** [comment]
What you are describing is "anonymity" (not privacy).

Use Tor for anonymous Internet, a VPN can't help you with that.

**Comment by Yzord** [comment]
https://pando.com/2014/07/16/tor-spooks/

Tor isn't safe after all ;) and can you please tell me why VPN cannot give me anonymous access to the internet? Just saying it will not help me is not really true. That said, when you can multihop between servers.

**Comment by Nyr** [comment]
> https://pando.com/2014/07/16/tor-spooks/

Haven't read the entire article but US government funding doesn't make Tor insecure or anything like that. Looks sensationalist to me.

> can you please tell me why VPN cannot give me anonymous access to the internet

Because it was not designed for that. OpenVPN is intended for establishing secure connections over insecure links, not for anonymity.

> Just saying it will not help me is not really true.

It would be useless in nearly any threat model I can think of. A VPN connection is not anonymous per nature, so multiple VPN connections don't achieve a higher level of anonymity. I have no clue about your adversaries capabilities or your needs so can't comment any further.

The fact is that there are plenty of high profile cases where powerful adversaries (aka western governments) weren't able to identify users of the Tor network. The same can't be said for nearly any case involving a VPN instead.

Anyway I don't really care about this kind of discussions and I don't think this issues tracker is the right place to have them.
