### ISSUE TITLE
Host unreachable

### ISSUE THREAD

**Issue by technodrome** [Nyr/openvpn-install#185]
Hi, 
I run into problems with OpenVPN client. I cannot connect. All I get is: 

`read UDP [EHOSTUNREACH]: No route to host (code=113)`

I disabled the firewall on my box, policy is accept everything. Still no luck. 
Checked from another machine whether UDP 1194 is open - it says it is filtered so I have no other way of checking. 
I have tried this with the same result on Android 6.0.1 and 5.1.1, both cyanogenmod. The client works for my other Synology VPN box in a different country so it cannot be faulty. There is no subnet clash, I tried to connect with my mobile data connection but it results in the same error message. 

Android OpenVPN client log - [2016.txt](https://github.com/Nyr/openvpn-install/files/442133/2016.txt)

Any help please?

**Comment by Nyr** [comment]
Not a problem with the script.

Looks like you have also made some modifications (for example, trying to use AES-256-CBC which is not the default defined by the script configuration).

Regards

**Comment by technodrome** [comment]
Thanks for speedily dismissing my problem. I was using https://github.com/Angristan/OpenVPN-install, which is a fork of your script. As there is no issue tracker, I used yours. 

Anyway, now I installed your script and the net result is exactly the same. I attached the log. Please note, IP is changed.

[debug.txt](https://github.com/Nyr/openvpn-install/files/453633/debug.txt)

**Comment by Nyr** [comment]
First of all, I don't support forks for obvious reasons (didn't create or maintain them, don't even know about most of them). If the original creators don't want to provide support, I can understand that, but that's not my problem.

Anyway, as already mentioned: this is not an issue with the script, that's why it was dismissed. This is a tracker to address issues related to the script, not to your network.

The host 81.101.20.200 is currently not reachable on port 1194 UDP. I created a OpenVPN installer, I can't manage your firewall/NAT/whatever. My suggestion is to get it working on a clean set up and then implement whatever firewalling you need.

**Comment by technodrome** [comment]
I understand why you don't support work of other people. While I do, many programmers at least offer some hint, as this can happen to anyone. We are all people who need help from time to time. Given this simple bit of human understanding, your replies are arrogant at the very least and not contributing anything to the original problem, just throwing blame at me for something I have no control over. You are the author of the script. My server is in DMZ with firewall down. Don't tell me this is my problem, then, when many other services including nginx, mysql, redis etc are up and reachable - just your VPN server is not. My network is OK and I have not asked you to fix it. Nor did I ask you to reformulate the error message. If this is tracker to address issues, you definitely did not address them.

I will not be using your work in the future and definitely not recommend it to other people. It's not because of the quality of your work, or lack thereof. Your coding may be all right, but your demeanor definitely is not. 

Consider this issue closed.

**Comment by Nyr** [comment]
I already mentioned that there is very likely a problem with your network. Maybe you are forwarding TCP instead of UDP, I have no clue. The only thing I know is that your server is unreachable from the internet so yeah, the problem is very likely in your end.

You seem to ignore my advice and keep going round in circles. Whatever.

**Comment by PymatFlow** [comment]
I solved it by opening the port that OpenVPN uses.
