### ISSUE TITLE
Unable to ping clients from OpenVPN Server

### ISSUE THREAD

**Issue by vik-y** [Nyr/openvpn-install#190]
I installed this OpenVPN on my server using this. My VPN is working properly without any issues but I wanted to interconnect the hosts which are connected to my VPN. 

Host A : 10.8.0.2
Host B : 10.8.0.3

VPN Server S : 10.8.0.1

When I ping B to S it works. 
When I ping from A to S it works. 

But I can't ping from S to A and S to B. 
And because of that I can't ping from A to B. But both A and B are able to access Internet without  any issues. 

While breaking my head with the problem I decided to capture traffic on my vpn server using tcpdump. 

I used the 
```sh
tcpdump -i tun0 | grep ICMP 
```
to capture traffic. 

```sh
# Now in Host A, if I do 
ping 10.8.0.1 
# then the packet capture on vpn server is this. 

12:43:41.492078 IP 10.8.0.1 > 10.8.0.2: ICMP echo reply, id 6757, seq 1, length 64
12:43:42.496108 IP 10.8.0.2 > 10.8.0.1: ICMP echo request, id 6757, seq 2, length 64
12:43:42.496134 IP 10.8.0.1 > 10.8.0.2: ICMP echo reply, id 6757, seq 2, length 64
12:43:43.496314 IP 10.8.0.2 > 10.8.0.1: ICMP echo request, id 6757, seq 3, length 64
12:43:43.496346 IP 10.8.0.1 > 10.8.0.2: ICMP echo reply, id 6757, seq 3, length 64
12:43:44.495899 IP 10.8.0.2 > 10.8.0.1: ICMP echo request, id 6757, seq 4, length 64
12:43:44.495922 IP 10.8.0.1 > 10.8.0.2: ICMP echo reply, id 6757, seq 4, length 64
12:43:45.500215 IP 10.8.0.2 > 10.8.0.1: ICMP echo request, id 6757, seq 5, length 64
12:43:45.500236 IP 10.8.0.1 > 10.8.0.2: ICMP echo reply, id 6757, seq 5, length 64

# This shows that ping is working properly.

# Now when I ping from VPN Server S to Host A using command 
ping 10.8.0.2 # in server S 

the packet capture running captures the following
22:15:16.867718 IP 139.59.5.xx > 10.8.0.2: ICMP echo request, id 2886, seq 10, length 64
22:15:17.867828 IP 139.59.5.xx > 10.8.0.2: ICMP echo request, id 2886, seq 11, length 64
22:15:18.870699 IP 139.59.5.xx > 10.8.0.2: ICMP echo request, id 2886, seq 12, length 64
22:15:19.869963 IP 139.59.5.xx > 10.8.0.2: ICMP echo request, id 2886, seq 13, length 64

# and host A is not responding to these ICMP packets. What could be the problem?

#when I change 
server 10.8.0.0 255.255.255.0
#to 
server 10.8.1.0 255.255.255.0 
#then the problem gets solved, A can ping B, B can ping A and everyone can ping everyone, everyone is happy.. but Internet stops working on A and B. 

#Please help. I have broken my head over this problem for very long time now.  
```

**Comment by Nyr** [comment]
The "road warrior" setup was not intended for this, internal networking is intentionally not working. Still, this can be easily changed.

If you take a look at the script, you'll see the following rule being used:

`iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -j SNAT --to $IP`

If instead you add an exception for the VPN subnet, internal networking will work:

`iptables -t nat -A POSTROUTING -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to $IP`

I hope this helps.

PS: I always get notified of new issues opened here. I don't appreciate you spamming my personal email and demanding a "quick response".

**Comment by vik-y** [comment]
Thanks a ton. I tested it and it's working perfectly fine.


I completely missed out the email notification part. Sorry for the spam again.


________________________________

**Comment by aliradd** [comment]
Hi @Nyr thank you very much for this repo and for your reply here. I have a question for you please and I hope this is the right place to ask it.
I now have everything working in terms of my vpn clients can ping the server and the server can ping the client.
I have another machine on the server side.  So lets say:
S: Server local IP: 172.3.47.86
O: Other machine: 172.3.4.233

O and S can ping each other.
S can ping A and B
How can I get O to ping A and B please?
I added a route on O to 10.8.0.0 and set the gateway to S.
But S can not ping A.
Btw A can ping S.
Pleasse let me know if you like me to raise another ticket.
Best,
A

**Comment by Nyr** [comment]
> I hope this is the right place to ask it

It is not, I would suggest at least a new issue because this question is unrelated, but the issue tracker is not really a support forum.

> S can ping A and B
> But S can not ping A.
> Btw A can ping S.

I don't understand that, it is contradictory. I don't even understand where are A and B, are they VPN clients I guess?

Anyway, you have two options:
- Connect everyone needing access to the VPN server
- Set up routes on the VPN server so clients can connect to hosts in the network which is available to the server but not the client. You need to push those routes to the clients. Check the OpenVPN forums if you need specific instructions for that.

**Comment by aliradd** [comment]
Hi @Nyr 

>> I hope this is the right place to ask it

> It is not, I would suggest at least a new issue because this question is unrelated, but the issue tracker is not really a support forum.

Thank you very much for your reply :)
So fair point and fair point.
I was just intending on extending the question above and the scenario discussed. Obviousely I was not clear enough :)
The idea is A,B and S are the servers per this issue.
And the Ovpn has been set up per your repo and has the changes above to allow A and B to talk added inside the clint side network (VPN subnet internal networking) 

>> S can ping A and B
>>But S can not ping A.
>> Btw A can ping S.

> I don't understand that, it is contradictory. I don't even understand where are A and B, are they VPN clients I guess?

A,B and S are per the issue ticket.
O is on S side Lan.
I should have said A and B can ping O currently.

> 
> Anyway, you have two options:
> 
> Connect everyone needing access to the VPN server
> Set up routes on the VPN server so clients can connect to hosts in the network which is available to the server but not the client. You need to push those routes to the clients. Check the OpenVPN forums if you need specific instructions for that.

A,B and S can ping birecetionaly, once I "add an exception for the VPN subnet"
A and B and S can ping O
S and O can ping birecitionally.
O can't ping A nor B
O and S are on the same LAN.

If you are able to help here without too much hassle then I shall move this onto an issue.
Otherwise thanks for your response and I shall try the forums.
Best.

**Comment by Nyr** [comment]
@aliradd 

- The changes described in this issue to enable internal networking are no longer relevant. Internal networking was enabled some time ago in the script.
- This is what you want: https://openvpn.net/index.php/open-source/documentation/howto.html#scope

**Comment by aliradd** [comment]
Hi,
Thank you very much for your reply. Just ping me if you think this needs a different issue and I would be happy to create one.
All the best,
A.

**Comment by theiphoner** [comment]
Best Regards,
Ibrahim Almalki

**Comment by podguzovvasily** [comment]
Dear @Nyr Time passed and the script changed. How can I fix it now so that devices on the network can communicate with each other? 

ExecStart=$iptables_path -t nat -A POSTROUTING -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to $ip
ExecStart=$iptables_path -I INPUT -p $protocol --dport $port -j ACCEPT
ExecStart=$iptables_path -I FORWARD -s 10.8.0.0/24 -j ACCEPT
ExecStart=$iptables_path -I FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
ExecStop=$iptables_path -t nat -D POSTROUTING -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to $ip
ExecStop=$iptables_path -D INPUT -p $protocol --dport $port -j ACCEPT
ExecStop=$iptables_path -D FORWARD -s 10.8.0.0/24 -j ACCEPT
ExecStop=$iptables_path -D FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT" > /etc/systemd/system/openvpn-iptables.service
                if [[ -n "$ip6" ]]; then
                        echo "ExecStart=$ip6tables_path -t nat -A POSTROUTING -s fddd:1194:1194:1194::/64 ! -d fddd:1194:1194:1194::/64 -j SNAT --to $ip6
ExecStart=$ip6tables_path -I FORWARD -s fddd:1194:1194:1194::/64 -j ACCEPT
ExecStart=$ip6tables_path -I FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
ExecStop=$ip6tables_path -t nat -D POSTROUTING -s fddd:1194:1194:1194::/64 ! -d fddd:1194:1194:1194::/64 -j SNAT --to $ip6
ExecStop=$ip6tables_path -D FORWARD -s fddd:1194:1194:1194::/64 -j ACCEPT
ExecStop=$ip6tables_path -D FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT" >> /etc/systemd/system/openvpn-iptables.service
WantedBy=multi-user.target" >> /etc/systemd/system/openvpn-iptables.service

Or is it even possible to do this without restarting the script? Thank you! Happy New Year.

**Comment by podguzovvasily** [comment]
Thanks! I'll keep that in mind
