### ISSUE TITLE
Quick question: What are script defaults?

### ISSUE THREAD

**Issue by AaronJWhite** [Nyr/openvpn-install#203]
Besides OpenVPN what does this script install or configure on the server? I didn't see this info in the read.me so sorry for the simple question. I have a server already that I use to host my own gitblit with Apache and some iptable rules. Trying to figure out if the defaults for this script will break anything. Thanks!

**Comment by Nyr** [comment]
Good question, actually :)

I'm on some heavy medication so sorry in advance if I miss something:
- It installs OpenVPN using the system package manager (either `apt-get` or `yum`).
- It downloads `easy-rsa` to the OpenVPN dir. This is just a set of scripts for certificate generation.
- It enables `net.ipv4.ip_forward` on `sysctl` so traffic can be forwarded.
- It sets NAT rules so VPN clients can reach the internet from the server.
- It adds additional exceptions to allow OpenVPN traffic on the firewall if that's needed.

One of the main reasons why I started developing this script, was because I wanted some clean work which wouldn't mess with the rest of your system and which was easy to maintain or even remove if needed.
