### ISSUE TITLE
Connection constantly dropping Windows 8 and 10

### ISSUE THREAD

**Issue by transonly** [Nyr/openvpn-install#219]
From my other linux's it works great but from W10 and 8 is undoable.
I'm using both the 32 and 64 client obtained here https://openvpn.net/index.php/open-source/downloads.html
It connects well to drop it in a few minutes and sometimes giving me

`Fri Nov 04 08:30:01 2016 [server] Inactivity timeout (--ping-restart), restarting
Fri Nov 04 08:30:01 2016 SIGUSR1[soft,ping-restart] received, process restarting
Fri Nov 04 08:30:03 2016 UDPv4 link local: [undef]
Fri Nov 04 08:30:03 2016 UDPv4 link remote: [AF_INET]212.114.111.165:1194
Fri Nov 04 08:30:03 2016 [server] Peer Connection Initiated with [AF_INET]212.114.111.165:1194
Fri Nov 04 08:30:05 2016 Preserving previous TUN/TAP instance: Ethernet
Fri Nov 04 08:30:05 2016 Initialization Sequence Completed`

Then i can browse the web again till it drops again and again and again.
if you want to play with it i can send you a .ovpn so you can see?

**Comment by transonly** [comment]
Editing /etc/openvpn/client-common.txt and added keepalive 10 120 seems to do the trick.

**Comment by transonly** [comment]
It most definitely did the trick. Added line also works well on my linux so perhap you should include it on the /openvpn-install.sh ?

**Comment by transonly** [comment]
It most definitely did the trick. Added line also works well on my linux so perhap you should include it on the /openvpn-install.sh ?

**Comment by transonly** [comment]
It most definitely did the trick. Added line also works well on my linux so perhap you should include it on the /openvpn-install.sh ?

**Comment by transonly** [comment]
It most definitely did the trick. Added line also works well on my linux so perhap you should include it on the /openvpn-install.sh ?

**Comment by transonly** [comment]
Hm, occasionally still loosing connection but not so often. Suggestions?

**Comment by YassinOufkir** [comment]
Are you doing this from your home network or somewhere else?

**Comment by transonly** [comment]
My setup: Debian 8 (fresh install from ISO apt-get update and upgraded first) on rented VPS with the openvpn installed by the openvpn-install.sh with the defaults and encryption for the fastest connection.
At home i connect through a reliable broadband fiber.
Both pc's with windows 8 and 10 are connected to the modem/router by wire so no wireless shit interfering etc. using the resp. clients obtained from https://openvpn.net/index.php/open-source/downloads.html.

**Comment by transonly** [comment]
another thing when viewing the iptables it shows

    iptables -L
    Chain INPUT (policy ACCEPT)
    target     prot opt source               destination

    Chain FORWARD (policy ACCEPT)
    target     prot opt source               destination

    Chain OUTPUT (policy ACCEPT)
    target     prot opt source               destination

There's no firewall on but shouldn't this dow something else?

**Comment by Nyr** [comment]
iptables doesn't show the NAT because you aren't requesting that. Try instead: `iptables -t nat -L`

Anyway, this doesn't have anything to do with your problem:

- `keepalive 10 120` is already being used on the default configuration with this script.
- Editing `/etc/openvpn/client-common.txt` will only change settings for further generated client configuration files, not current ones. It's not the right place to edit settings.
- `keepalive` should be used server-side, so the server also pings the client. Using it server-side, automatically pushes the same params to client. To do this, edit `/etc/openvpn/server.conf` and restart OpenVPN.
- If you are actively using your connection and it's dropping, `keepalive` should have zero effect in improving the situation.
- Try setting `keepalive 10 3600` on the server. This will send a ping in both directions each 10 seconds and only trigger a `ping-restart` if the destination was unreachable for a whole hour. This workaround could "fix" your situation.
- If after that this is still an issue, check packet loss between client and server. If it is happening, you'll need to fix that.

For further information please refer to the OpenVPN manual. This is, again, not an issue with the script.

**Comment by transonly** [comment]
Ok, thanks for answering again since it's not a script issue.

To be clear 

- i know that editing /etc/openvpn/client-common.txt is not the place but it gets created on installing so that's why i edited the file directly and created new profiles.

- so the ovpn file should not show an entry for the keep-alive? By default it isn't there. Because you're writing "so the server also pings the client". They should both be pinging?

I've edited the server.conf keep-alive 10 3600 and restarted with /etc/init.d/openvpn restart and will see how it behaves.

**Comment by Nyr** [comment]
> so the ovpn file should not show an entry for the keep-alive?

Right. The `keepalive` settings are pushed from the server to the client while establishing the connection. Putting them in the client configuration file would be redundant.

> They should both be pinging?

Yes, OpenVPN pings do not work like ICMP echo which is what most people is used to. They don't get echoed, so each side must be told to ping the other side.

**Comment by transonly** [comment]
Well, ok. Also with the keep-alive 10 3600 the connection drops from time to time. I must have very exotic Windows machines giving me this trouble and i wished there was a openvpn server somewhere that is undoubtedly configured right to see my clients also messing things up. 
I'm just running your script and installing the clients as provided by openvpn themselves  so i really don't understand why the internet is not filled with solutions regarding my problem here. ;-)
Thanks so far and i'll post back if i know what is messing things up iver here.

**Comment by Nyr** [comment]
You could also try editing `proto udp` to `proto tcp` in both `/etc/openvpn/server.conf` and the client `.ovpn`.

**Comment by transonly** [comment]
Makes sense since udp doesn't care if packets get lost or not. udp is the choice om reliable networks and because its faster?
Trying right now with Tcp.

**Comment by Nyr** [comment]
Yeah, UDP is faster. And TCP over TCP is generally not a good idea.

**Comment by transonly** [comment]
I can see in there's some debate over that and why would it even be possible if it's such an horror to do so? Still having a solid connection now for more than an hour using TCP.

**Comment by Nyr** [comment]
It's not horrible, there are some use cases.

For example, a TCP VPN is useful to carry UDP connections over an unstable network. Another example is TCP on port 443, often used to connect from restricted networks.

It is possible that TCP support will be added to the script along with some advanced settings, but no promises. I don't want it to be an user-facing option.

**Comment by transonly** [comment]
I came across this [webpage ](https://workaround.org/openvpn-faq/)and read this:

keepalive 1 5
persist-tun
persist-key
persist-local-ip
persist-remote-ip
push "persist-key"
push "persist-tun" 

Switched back now to udp and it seems that the connection is now stable over udp.

I don't see the following lines in your server.conf
push "persist-key"
push "persist-tun"

**Comment by Nyr** [comment]
> I don't see the following lines in your server.conf
> push "persist-key"
> push "persist-tun"

Because those are unneeded. They are used in the server so it can restart even after dropping privileges, but the client doesn't work like that.

> keepalive 1 5
> persist-tun
> persist-key
> persist-local-ip
> persist-remote-ip
> push "persist-key"
> push "persist-tun"

If you are using all those mentioned settings, and you don't notice cuts any longer, it's not because the connection has magically become stable: you are just failing to notice blips since they are detected way sooner (`keepalive 1 5`) and you are preserving state during renegotiation (`persist-*`).

While it is possible that this has made your problem kind of unnoticeable for the average user, it hasn't solved it and I don't implement new settings into the script in "works for me" basis.

**Comment by transonly** [comment]
push "persist-key"
push "persist-tun"
keepalive  1 5

is what i added to your config file.

I will remove them and see what happens and post back.
The settings where copied from the website i referred to so you could look it up.

**Comment by Nyr** [comment]
Then the only thing you are doing is not shutting down the client TUN interface between restarts and shortening the keepalive a lot.

I insist: that will not fix any stability problems, just can make them less noticeable.

**Comment by transonly** [comment]
And why can't i see the ping on the Tap monitored by wireshark?
And are you only doing things on Linux? Have you tested it all on your own machines with windows?

**Comment by Nyr** [comment]
> And are you only doing things on Linux? Have you tested it all on your own machines with windows?

I don't personally use OpenVPN clients in either Windows or Linux, but testing has of course been performed there when OS specific issues happen. Anyway I assume that most users of this script are actually running Windows clients.

> And why can't i see the ping on the Tap monitored by wireshark?

- The script is doesn't set up TAP
- OpenVPN keepalive ≠ ICMP ping

There is nothing wrong with the script regarding this issue you have. Maybe some configuration changes can make it less noticeable (frequent keepalives and persistence) or even fix the disconnections (using TCP), but ultimately the problem is in your end.

I suggest you to seek help elsewhere, since this is a tracker for issues with the script and I can't fix an unstable connection. Some workarounds have already been provided anyway, and they seem to be working for you.
