### ISSUE TITLE
Server with 8192 bit key?

### ISSUE THREAD

**Issue by Stsosz** [Nyr/openvpn-install#23]
Would it be possible to adapt this script to work with 8192 bit keys, or prompt for a key size out of several sizes? (1024, 2028, 4096, 8192)

**Comment by frantzz** [comment]
Hey Nyr,
can you please tell me why this is "stupid" ?
I'm new to this OpenVPN technology. I thought when the "bits" is higher it has more security ?

**Comment by smeggysmeg** [comment]
I think the issue is that, with increased encryption, you will have
increased overhead. Increased overhead will result in a significant hit to
performance. Since lesser encryption levels are nearly impossible to break,
it serves no purpose to provide such a high encryption option; it's just
choosing a higher number for the sake of it being higher, with no practical
benefit to security. This script is designed to provide a quick and
conventional setup, and providing for such an extreme encryption option is
neither conventional nor particularly useful.

**Comment by frantzz** [comment]
Thank you for your reply smeggysmeg.

**Comment by Nyr** [comment]
@smeggysmeg is mostly right.

Also, key length has nothing to do with the cipher used to secure the transmission, which is a common misconception.
