### ISSUE TITLE
Sudden appearance of issue on previously working install

### ISSUE THREAD

**Issue by nihalf** [Nyr/openvpn-install#233]
Hi Nyr, I'm a huge fan of your installer and have been recommending it to plenty of people, because it 'just worked' out of the box for me. I've been using it for a year and a bit now, with no hassles. But last week, I used it with a cafe Wifi (and it worked fine) and ever since then ovpn fails to connect. The relevant logs are 
as follows:

Sun Dec 04 17:10:37 2016 CreateFile failed on TAP device: \\.\Global\{CFFF023D-EC1F-41BB-AF9B-7F1A6898B6A0}.tap
Sun Dec 04 17:10:37 2016 MANAGEMENT: Client disconnected
Sun Dec 04 17:10:37 2016 All TAP-Windows adapters on this system are currently in use.
Sun Dec 04 17:10:37 2016 Exiting due to fatal error

Any idea how to fix this? I've googled how to add TAP-Windows adapters, but thought I should check in with you first on what avenues I should consider before messing about too much

**Comment by Nyr** [comment]
This is a client-side issue, so did you try reinstalling the OpenVPN client? This will remove the driver and hopefully resolve whatever was wrong.

If it still doesn't work, take also a look at [this](http://stackoverflow.com/questions/14896590/openvpn-failed-connection-all-tap-win32-adapters-on-this-system-are-currently). Other than that, I don't use Windows and have never seen this, so can only wish you good luck with it.

Closing since this isn't an issue with the script, but feel free to continue troubleshooting here if someone else can help. And hopefully tell us if you end up fixing it :)

**Comment by nihalf** [comment]
Fair play, also re-installing the OpenVPN client worked. I know, I should have done that to start with, but I hate the turn-it-off-and-on-again style of dealing with issues. Prefer to try and learn something from troubleshooting issues... and yes, I really need to get off Windows, but, what can I say, inertia is a biatch.

Thanks again mate, you're a legend.

**Comment by Nyr** [comment]
Windows is fine, I consider it a matter of personal preference :)

Happy to know it was resolved.
