### ISSUE TITLE
Feature Request: Select protocol

### ISSUE THREAD

**Issue by muhammad-saleh** [Nyr/openvpn-install#238]
Hi,
Thanks a lot for your script it's awesome :)

One thing still, Can you please add the option to select which protocol to use [TCP or UDP] ?
This helps to tunnel the traffic to 443 TCP
Yeah we can do that manually but it helps if it was in the script as well

Thanks again :)

**Comment by Nyr** [comment]
This is by far the most requested feature and it would take like 30 seconds to implement ;)

If it has not been implemented already, it is because I try to keep the installer as simple and beginer-friendly as possible. Many users don't really understand the differences between OpenVPN over UDP and TCP and most don't care about TCP, so at the current time there is no selection for that.

I understand others want this to be an option, but for now that's how it is.
