### ISSUE TITLE
ipv6 support?

### ISSUE THREAD

**Issue by mrh1gh** [Nyr/openvpn-install#242]
Hi, its possible to add ipv6 support? How can i reach this?

**Comment by VBQL** [comment]
Yes but the entire routes of ipv6 is very unstable. Some people don't even have ipv6 yet. I would not suggest ipv6 to be implemented currently. You can check all of the closed ipv6 request posts.

**Comment by Nyr** [comment]
Yeah, it is sadly not viable right now.

**Comment by JMoVS** [comment]
@Nyr One question: Is it possible to give the client an ipv6 address? Connecting via ipv4 is reasonable, but if the vps has ipv6 connectivity, isn't it possible to configure openvpn to allow a passthrough of that to the client?

**Comment by Nyr** [comment]
@JMoVS it depends. Assigning IPv6 for OpenVPN clients is as simple as enabling IPv6 forwarding within sysctl and setting an available subnet in the OpenVPN server configuration.

The main problem is that OpenVPN needs a routable subnet with a size between /112 and /64. This is not available in most VPS, you instead can assign individual /128s from whatever subnet the provider did give you and this will not work with OpenVPN. As a workaround you could use IPv6 NAT if your system supports that.

Given the current status of IPv6 in general and with OpenVPN particularly, don't expect it to be implemented within the script anytime soon. Not because I don't want to, but because it is not realistic as long as IPv6 continues to be so broken.

**Comment by JMoVS** [comment]
@Nyr Hmm. Looking at my VPS's ip address that I gathered via `ip -6 addr`, and it ending in ':1/112` I guess I have a /112? So what would I need to change in this script (possibly fork) to get it to work so it passes through ipv6 traffic but connects to the server over ipv4 for connection? I can try to research it, just wanted to know if you know any good sources of info directly

**Comment by Nyr** [comment]
@JMoVS that means you have a single IPv6 address within that range currently added to the VPS. It does not necessarily mean that you got the entire subnet available to route as needed.

If you really have a fully routable /112 (which is very rare for a VPS):

1. Enable IPv6 forwarding in `/etc/sysctl.conf` adding/editing`net.ipv6.conf.all.forwarding=1`

2. Run `sysctl -p` to load changes.

3. Edit `server.conf` adding:
```
server-ipv6 2001:1234:5678:9::/64 # your subnet (/112 in your case)
push "route-ipv6 2000::/3" # tell client to route IPv6 traffic via the VPN
```

I've written that mostly from memory, but that should be it if your /112 is entirely available as a full subnet for your server, which again is very rare for a VPS. Since you probably don't have the entire subnet available, my suggestion is to either do NAT or better: forget about it. The status of IPv6 currently sucks almost everywhere and IPv6 internet is nearly always slower anyway.

Whatever you want to go from here is your choice, but do further research yourself since this is not related to the script anymore.

Good luck.

**Comment by JMoVS** [comment]
@Nyr Just checked with my VPS provider, I have a /64 net (at least that's how they phrase it). Well, I'll research a bit more. Thank you so far!

**Comment by Thomvh** [comment]
Wouldn't it be possible to do NAT ipv6? Then you only need one ip? Pritunl is doing that already.

**Comment by Nyr** [comment]
@Thomvh possible, yes.

But not planned in the short term, both because IPv6 NAT is not supported in every environment and because that is a “dirty” way to do IPv6.

You shouldn’t expect IPv6 in this project anytime soon.

I don’t want to be pessimistic, but for now, enabling IPv6 usually just means getting access to a worse, less peered, slower internet.

**Comment by Thomvh** [comment]
@Nyr Pessimistic is not good ;)
In my own experience and looking at my home ntopng stats. Nearly 21% of my traffic is ipv6. 
No hard feelings but it was just a thought on how to future-proof this project!

**Comment by Thomvh** [comment]
@Nyr I know, its a shame.
