### ISSUE TITLE
Do default configuration values favor performance?

### ISSUE THREAD

**Issue by tapir** [Nyr/openvpn-install#243]
Hi,

I've been using your script for a while now. It really makes the process a lot easier.
One thing I've noticed though the performance is really bad.

Here is how it looks without VPN
![capture2](https://cloud.githubusercontent.com/assets/223984/21515629/771aaf36-cce2-11e6-864f-a4372211293c.PNG)

And with VPN
![capture](https://cloud.githubusercontent.com/assets/223984/21515704/0e6bc910-cce3-11e6-9749-015a46331452.PNG)

This is running on a Vultr 4 core, 4GB, SSD VPS. The machine is definitely not pushed to the limit. Resources are plenty. I've even tested their network and the VPS performance by doing a speed test with SSH proxy instead of VPN and the speeds are very close to the no VPN graph.

Any ideas? Could this be related to OpenVPN configuration?

Thanks

**Comment by Nyr** [comment]
The script is quite "performance friendly". It is designed to maintain a good balance between performance and security, but it is not likely that processing power is the bottleneck here.

There are many other factors to consider and a speed test isn't always a good measure of real internet performance:

- Is the speed test data compressible? This is a factor to consider when testing over protocols which have compression enabled by default.

- Does your ISP suck? This is a very real possibility. 2 ms of latency suggests that the speed test server is located inside their network or with extremely good direct peering. This is not representative of real performance and a dishonest practice often done to confuse customers.

- Is the VPN route congested at any point? Again a very real possibility and related to the second point, we would need to investigate further to determine that. Except in New Jersey, Vultr network is not that good in my experience. At least it was the case some time ago. This can be combined with a shitty domestic ISP for disastrous results.

My suggestion is to maybe try a different ISP for the server. One closer to you and hopefully with either direct peering or quality transit to your domestic ISP.

I'm closing since this isn't an issue with the script, but feel free to let us know if you perform further troubleshooting.

**Comment by tapir** [comment]
Thanks. I will investigate further. One thing that led me to believe that this might be a configuration issue was that when I run the speed test through a SSH proxy to the same server intead of VPN, the speeds are OK. So that I think leaves ISP faults out.

**Comment by Nyr** [comment]
Well, not all kinds of connections and protocols perform the same over one line. Try OpenVPN over TCP maybe? UDP usually has lower priority with many ISPs.

Other than that, make sure you are using a relatively recent version of the script, it did implement some improvements on the buffers.

**Comment by DonZheng** [comment]
Dear Nyr,

Thanks for the great script which makes setting up OpenVPN server so much easier.

You mentioned that current script 'maintains a good balance between performance and security'. Wondering if you can please share some expertise on how to twist the script to favor either performance or security? 

A bold idea is we can add an option at the start of the script and let script user pick among 'Performance Favored', 'Security Favored', 'Balanced'.

Kind Regards

**Comment by Nyr** [comment]
@DonZheng the script is pretty secure as is and generally speaking, "upgrading security" would only decrease performance without improving real world security. Performance wise, the configuration is also pretty fast and shouldn't cause bottlenecks except in very slow systems or very fast connections, but improving performance would require way too many sacrifices to be worth it.

**Comment by DonZheng** [comment]
Dear @Nyr,

Thank you for your prompt reply, as always.

Could you please share some guidance on what one should do to achieve
maximized performance, and what sacrifice/compromise is at cost?

I have googled around but most threads are too broad. In the context of
your working script, I hope we can get more executable advice from you.

THanks in advance

**Comment by TinCanTech** [comment]
The developers at OpenVPN take great care to ensure the best balance of security verses performance.

**Comment by Nyr** [comment]
Anyone wanting to divert from the very sane defauts configured by this script should do their own informed research. For 99.9% of the users the default choices are the best option and for the rest, they should know their own specific needs (I don't).
