### ISSUE TITLE
Disclose affiliate link

### ISSUE THREAD

**Issue by Sup3rLativ3** [Nyr/openvpn-install#249]
I personally don't have an issue with affiliate links but perhaps just being transparent about it would be nice.

**Comment by Nyr** [comment]
I think the `aff.php?aff=xxx` part is transparent enough, not hidden behind an URL shortener or anything like that.

Considering the number of hours directly or indirectly invested over the last few years, anyone considering that I'm turning a profit on this project is out of his mind (just saying, not suggesting you do).

**Comment by Sup3rLativ3** [comment]
I'm not suggesting that you haven't worked hard or that you don't deserve
it but the link is hidden behind the text. Considering your user base they
may not check their links or even know about affiliate links out how to
check them. At the end of the day it's your project but thought I would let
you know how it could possibly be interpreted.

**Comment by Nyr** [comment]
> how it could possibly be interpreted

I hope people interprets it as "this guy is having a beer on me", because that's the truth. I do the project because I want to and because I use it myself, my motivations would be the same, affiliate link or not.

In the interest of full disclosure, I will show my profits from the affiliate link so far on this month:

![captura de pantalla 2017-01-17 a las 13 29 25](https://cloud.githubusercontent.com/assets/739489/22020644/9926b28c-dcb9-11e6-8676-8a6900798b4e.png)

Let's do the math: that's $1,32 comission so far for this month, about the cost of a bottle of beer in my city. Considering that I drink mostly pints, at the end of the month I will be able to get one of them from my affiliate profits :)

(Yes, I get what you are trying to say, it just doesn't bother me much considering the situation.)
