### ISSUE TITLE
cannot connect to internet after vpn server restart

### ISSUE THREAD

**Issue by CrispiesOne** [Nyr/openvpn-install#267]
I set this up on centos 7 on vultr and when i do a restart of the server I no longer get internet when connected to the vpn. a couple of suggestions to if you are open. Might want to change the encryption away from sha1 since it has been broken and way to add multiple users at once would be nice.

**Comment by Nyr** [comment]
Sorry for the late response.

Can confirm the issue. Should be a simple fix, but I'm unable to further troubleshoot due to health issues.

My hope is that I will be able to recover and submit a bugfix soon, but can't provide much of a timeline since I suffered an issue which could've affected my brain. Even trying to write in English is kinda difficult at the moment.

A workaround would be to put `sleep 10` on top of the rules saved in `/etc/rc.d/rc.local`.

**Comment by CrispiesOne** [comment]
get well soon man

**Comment by Nyr** [comment]
Thanks for the very useful report and sorry for the long time it took for a fix.

Investigating this I did also discover some other issues which had been fixed in the same commit.

Regarding the signature algorithm, SHA-256 is being used, not SHA-1. This is the easy-rsa default.

The choice to add multiple users at once is not planned, sorry.

Thanks again for the report.
