### ISSUE TITLE
User can not go in internet and not resolve internal dns 

### ISSUE THREAD

**Issue by francescodesiderio** [Nyr/openvpn-install#269]
Many thanks for this script, is very userfull.

I have this problem:

client is able to connect to vpn but after connection client does not go in internet and is not able to resolve internal dns.

I think is iptables and route problem but I am not able to fix.  My internal dns server have on network card with 192.168.10.254 ip and second network card used to go in internet with 192.168.1.1 ip.

**Comment by SquirrelCoder** [comment]
I don't think this problem is related to script. It would have been better if you could said, which Distro you are using! 
Anyway, I think this problem is related to ip masquerading. Just enable it, restart OVPN server, and you should be good to go.

**Comment by ttlequals0** [comment]
This is probably related to mssfix bug/

solution:
echo 'mssfix 1200' >> /etc/openvpn/server.conf

**Comment by Nyr** [comment]
Could be the same as https://github.com/Nyr/openvpn-install/issues/267, or could be that your server is behind a NAT and you are not setting that up [correctly](https://github.com/Nyr/openvpn-install/issues/138#issuecomment-196055353).

Either way I'm closing since it's either a duplicate or not an issue with the script.
