### ISSUE TITLE
No  WAN access

### ISSUE THREAD

**Issue by FelixPQ** [Nyr/openvpn-install#290]
Nyr, 

thanks for making this script available, it's just great. 

I probably missed something or yes I'm that dumb!

I've use your script and it works fine as long as I'm connecting from the local network. The ovpn file are created using my lan ip. I manually changed the remote line to my domain name (ddns) and though I can still connect using modified ovpn's, I doesn't seem to be working correctly, for example, I can't ping the 10.8.0.0/8 except my own of course. I assume it as to do with routing but I don't know how to fix it.

Here is what I'd like to be able to do, provide a few service say like a private web server, ssh server, samba shares would be nice (works fine when ovpn set to local ip), all this over the internet through openvpn and lastly I'd like to use names instead of ip's. My server as it's own firewall (ufw) and is connected to my isp router.
Thanks

**Comment by Nyr** [comment]
From what you say, WAN access is not what you need. For that you would need routing and a setup out of the scope of this issue.

I think internal networking between clients and the server is what you want, right? The script doesn't allow internal networking by default. This is intentional.

Take a look at [this](https://github.com/Nyr/openvpn-install/issues/211#issuecomment-258063856) for how to enable internal networking.
