### ISSUE TITLE
VPN not working on Ubuntu 16.04

### ISSUE THREAD

**Issue by Ammar7347** [Nyr/openvpn-install#335]
Not working on ubuntu 16.04.2

The problem is that in "nload", tun0 doesn't show up even though VPN is running. See screenshot:
![image](https://user-images.githubusercontent.com/19525838/27927801-5e696d88-62a6-11e7-969c-c97585bab51e.png)

**Comment by Nyr** [comment]
Please do not spam the issue tracker, you already reported this in #334.

This issue tracker is for problems with the script itself, your issue is not caused by the script (at least it doesn't look like so) and this is not the right place to ask for technical support. Use the OpenVPN forums instead.

**Comment by Ammar7347** [comment]
THIS is the right place to ask this question because if I manually configure using https://www.digitalocean.com/community/tutorials/how-to-set-up-an-openvpn-server-on-ubuntu-16-04 the OpenVPN, it works but when I use this script, VPN doesn't work. So basically, the problem is definitely "Script" related.

**Comment by Nyr** [comment]
I already told you to stop spamming and you keep cross posting your messages to two different issues. Every time you do that, lots of people are notified via email. To prevent further spam, you're now banned from this issue tracker.

I insist that the script is working on a clean system and the problem is in your side.
