### ISSUE TITLE
OpenVPN tcp mode support

### ISSUE THREAD

**Issue by skobkin** [Nyr/openvpn-install#336]
Can you add support for TCP mode?

MiktoTik and some other routers have only TCP support for OpenVPN and it's very disappointing that I need to choose between using VPN on my router and your nice script.

**Comment by Nyr** [comment]
TCP has been supported for quite a bit of time already. It can be selected during setup.

**Comment by skobkin** [comment]
Huh. Thanks. Seems like I need to reinstall my VPN instance.

It's sad that this script does not support "upgrade" of configuration to newer versions.

**Comment by Nyr** [comment]
> It's sad that this script does not support "upgrade" of configuration to newer versions.

It would require lots of work, because there are many changes which need to set new system settings and other things, it's not just the OpenVPN configuration itself. I understand that it would be ideal to have this option, but to be honest with you it's unlikely that it will ever happen.

By the way, thanks for being a loyal user, I kind of remember your avatar from somewhere!

**Comment by skobkin** [comment]
I know. I'm developer too. I'm just thinking out loud :)

Thank you for your very useful work.

**Comment by skobkin** [comment]
By the way is it possible to support configuration with UDP and TCP at the same time? May be with generation of config pair (`user-tcp.ovpn` and `user-udp.ovpn`)?

**Comment by Nyr** [comment]
Needs two daemons with separate configurations, subnets, etc... doable, but no plans to include it in the script, I think this is actually the first request ever for that, sorry.

**Comment by skobkin** [comment]
Okay. Thanks anyway.
