### ISSUE TITLE
Ability to disable LZO compression

### ISSUE THREAD

**Issue by skobkin** [Nyr/openvpn-install#340]
Some of clients (like MikroTik routers) does not support LZO.

It would be nice if there will be ability to disable LZO in the setup process (which will eliminate the need to manually edit server config and each of client configs).

**Comment by cerebrux** [comment]
Default are what @Nyr wants for the script. If you need more control, like the no-lzo you should use the fork https://github.com/Angristan/OpenVPN-install

**Comment by skobkin** [comment]
@cerebrux Thank you for pointing me to such a nice fork. But I didn't see an option to disable LZO compression on screenshots. Is it available in this fork?

**Comment by cerebrux** [comment]
Ah, you didn't read the "features" list ? It says no compression by default 😉

**Comment by Nyr** [comment]
I'm aware of the MikroTik situation, but the issue is with them not supporting very basic and standard OpenVPN features (UDP, LZO, etc...).

MikroTik doesn't care about implementing proper OpenVPN support and that's been the case for many years. Tell them to fix their broken client. Compression is desired for almost any road-warrior setup and as such I don't see much reason to disable that.

My advice is against using the suggested fork, given how clueless and irresponsive the creator is. Many of his "improvements" are certainly not improvements but personal preference, and some others are just false or even "stolen" from my commits. The creator is aware of my concerns and has even removed the "forked from Nyr/openvpn-install" part on his GitHub repo.

**Comment by skobkin** [comment]
@Nyr
> Tell them to fix their broken client

They already stated that they will not add support of this features.

> My advice is against using the suggested fork, given how clueless and irresponsive the creator is. Many of his "improvements" are certainly not improvements but personal preference, and some others are just false or even "stolen" from my commits.

I agree. But for end-user like me to have more configuration options is preferred. I'm not an "road warrior". I just need to have stable OpenVPN server with minimal efforts to make it work. If it will work with my router out of the box then it's my choice.

**Comment by Nyr** [comment]
> They already stated that they will not add support of this features.

Then they only want to support a very small subset of all the OpenVPN servers running nowadays and they are causing this issue themselves.

> If it will work with my router out of the box then it's my choice.

Good for you, but "works for me" is usually not my criteria when using/writing security software. Compression choice wasn't implemented in the fork, by the way: the feature is just disabled because the maintainer believes that it poses some kind of real security risk (it doesn't).

The only choices that the fork adds to my work are some irrelevant or buggy crypto choices and a different selection of DNS servers which is objectively worse. My defaults are widely accepted as secure, even if he claims otherwise.

Still, the fork is pretty popular, as it's common for many other VPN solutions where marketing comes before the facts. Thankfully, I don't have customers to impress with big words ;)

**Comment by skobkin** [comment]
> Then they only want to support a very small subset of all the OpenVPN servers running nowadays and they are causing this issue themselves.

I know and I agree. But this doesn't change anything.

> Compression choice wasn't implemented in the fork, by the way: the feature is just disabled because the maintainer believes that it poses some kind of real security risk (it doesn't).

I know. There are some strange statements in the README of that repo. But I don't see the reasons why it (LZO disabling) can not be implemented as an option in the original script. I wrote about it last time. If I continue to use your script then I'll be needed to change every `*.ovpn` file after generation if I disable LZO manually. I don't see any reasons why I can choose between UDP and TCP but can't choose betwen LZO and uncompressed stream.

If I was the author of this script, I would add an option to choose "recommended/default settings" or "advanced setting" (TCP/UDP, LZO/non-LZO, etc) and placed some flexible set of options in the second.

**Comment by no-replies** [comment]
It would be nice if the options were presented so can use with Mikrotik idiotic setup.

Sourced from: 
https://github.com/missinglink/mikrotik-openvpn-client
http://wiki.mikrotik.com/wiki/OpenVPN

**Comment by Nyr** [comment]
@no-replies the script doesn't set up compression anymore, so it should work with MikroTik clients in TCP mode (I hope).

**Comment by no-replies** [comment]
Its not working but not sure why. I think the tls auth is the issue

**Comment by Nyr** [comment]
@no-replies you are right, it seems like `tls-auth` is not supported in MikroTik.

TLS authentication in its current form was implemented by the OpenVPN developers in the year 2004, that was nearly 15 years ago. The MikroTik developers clearly don't care about a proper OpenVPN implementation.

The script is very conservative in supporting legacy systems, but this situation is a bit too much, sorry.

I suggest that you manually remove the two `tls-auth` lines if you want it to be hopefully compatible with MikroTik.

**Comment by no-replies** [comment]
I fully agree - It is a bit ridiculous and they don't even support encrypted dns in any form. 

Will try manual removal and see.

**Comment by skobkin** [comment]
@no-replies If it solves your problem with MikroTik OpenVPN client please tell us. It would also be very good if you can post here your diff of config files (excluding sensitive data of course).
