### ISSUE TITLE
Use real configuration management framework 

### ISSUE THREAD

**Issue by ageis** [Nyr/openvpn-install#351]
Look guys, Bash is fine and all, but this would be awesome as an [Ansible](https://docs.ansible.com/) role. Look into it.

**Comment by Nyr** [comment]
Not sure if you are trolling or serious.

I'm not going to rewrite the entire script just to add unneeded dependencies in the form of whatever configuration management framework is cool in the Bay Area this year.

The script does everything by hand, it's simple, clean, minimalist, well maintained and works with nearly no dependencies.

There is nothing wrong with its current form and I'm proud of it.

**Comment by Nyr** [comment]
I see that you edited your message. There are other projects in GitHub if you want something which is Ansible based.

You prefer Ansible, others would prefer Chef, others maybe Puppet, or Juju... sorry but I can't do them all. Bash is my choice and that will not change.

**Comment by ageis** [comment]
I wasn't trolling, I'm just trying to give you a little advice here. For some reason I received the impression you're a relatively young person? Correct me if I'm wrong. Trust me, I felt similarly 7 years ago; never thought I'd be doing anything other than PHP and Bash, but it's worthwhile to expand your skill-set, and you'll find that happening naturally as you take on new roles. You're absolutely right to be proud of your script. Indeed it's good work, which is how I stumbled upon it. Yes, there are already several OpenVPN Ansible roles, I've even worked on one myself. My favorite would be [Stouts.openvpn](https://github.com/Stouts/Stouts.openvpn).

Ansible isn't just a fad. Granted, my present place of employment uses Salt, which has its own issues, but ever since picking it up I think it's the best that's come along and will be here to stay, especially with the recent support from Red Hat. Puppet was a nightmare to me, and I've actually no Chef experience..  Look, I'm just suggesting to be open-minded in the future is all. There are limitations to shell script. Ansible modules are all intended to be idempotent, it's all done over SSH and thus doesn't require a manager/agent scheme, and effectively allows you to manage multiple hosts.

In this day and age, a lot of people don't just running some Bash script they got off the internet. Especially the the wget/curl pipe to superuser shell pattern which has been increasingly ridiculed in recent years. That's not to say that scripting isn't a valuable skill. It certainly is. 

If broken down into an automation module, this could be included as a single service or part in a system with many other components and configurations. There are many benefits to learning to automate the setup of things like OpenVPN. Shell scripts are suited for a lot of tasks but not ensuring system or service state IMO. For example, can I run your script a second time and be sure it won't break or clobber anything from the first go-around?

Anyway, I didn't mean any offense... Truly meant my comment in all friendliness. Best of luck with future endeavors.

**Comment by ageis** [comment]
Also, if you're interested in open source and having your code be usable and beneficial to other people, (not sure if you merely wrote this for yourself) but there aren't a whole lot of centralized shell script repositories (like CPAN, PCRE, PyPI, npm) etc. right? Yet these other frameworks have things like that (see Galaxy) where you could post it up for others to easily find, pull it down and use.

**Comment by Nyr** [comment]
I see that you have good intentions. I'll try to address some of your concerns:

> For some reason I received the impression you're a relatively young person? Correct me if I'm wrong. Trust me, I felt similarly 7 years ago; never thought I'd be doing anything other than PHP and Bash, but it's worthwhile to expand your skill-set

Unrelated to the script, but I'm 25 years old. Not sure if that's still young, I hope so!

I agree that it's an absolute necessity to keep expanding your skill-sets in IT. For the record, I'm not a developer and I can't even write PHP.

> Yes, there are already several OpenVPN Ansible roles, I've even worked on one myself. My favorite would be Stouts.openvpn.

From taking a quick look, it has very insecure defaults which shouldn't be used in the year 2017: cipher used is considered broken, as is the HMAC digest algorithm, or the RSA key length. The configuration is also DNS leaking for Windows 8/10.

I'm sure that the maintainer has good intentions when sharing his work, but it has serious security issues and he's offering it to third parties which are trusting his criteria.

> In this day and age, many security-conscious folks don't trust just running some random Bash script they got off the internet and haven't had a chance to review line-by-line. Especially with the wget/curl pipe to superuser shell pattern which has been increasingly ridiculed in recent years. 

Very reasonable. Thankfully my code is not that big and is decently organized (I hope), so doing a quick review is easy for anyone who can read some Bash.

> For example, can I run your script a second time and be sure it won't break or clobber anything from the first go-around?

Yes. It will detect the existing installation and let you do things like manage users or do a clean uninstall.

> Also, if you're interested in open source and having your code be usable and beneficial to other people, (not sure if you merely wrote this for yourself) but there aren't a whole lot of centralized shell script repositories (like CPAN, PCRE, PyPI, npm) etc. right? Yet these other frameworks have things like that (see Galaxy) where you could post it up for others to easily find, pull it down and use.

I written it because I needed it for myself. It has grown since then and now I feel like I have some kind of responsibility to keep it secure, maintained and updated.

I don't care that much about visibility, but my project currently ranks fifth when searching "install openvpn" in google.com, so it certainly has greater visibility than it would if hosted in any on the mentioned repositories.

The fact that it's written in Bash also makes it useful to a much bigger user base.
