### ISSUE TITLE
easyrsa-error when creating a user

### ISSUE THREAD

**Issue by Franzl123** [Nyr/openvpn-install#353]
hi,
i get an error when creating a new user (on omv 2.2.14).

here is the output:
```
Looks like OpenVPN is already installed

What do you want to do?
   1) Add a new user
   2) Revoke an existing user
   3) Remove OpenVPN
   4) Exit
Select an option [1-4]: 1

Tell me a name for the client certificate
Please, use one word only, no special characters
Client name: Silvie
Generating a 2048 bit RSA private key
......................................................+++
.......+++
writing new private key to '/etc/openvpn/easy-rsa/pki/private/Silvie.key.QFew2FXjaQ'
-----
./easyrsa: 644: ./easyrsa: [[: not found
Using configuration from ./openssl-1.0.cnf
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'Silvie'
Certificate is to be certified until Aug 28 22:01:57 2027 GMT (3650 days)

Write out database with 1 new entries
Data Base Updated

Client Silvie added, configuration is available at /root/Silvie.ovpn
```

**Comment by Nyr** [comment]
See https://github.com/OpenVPN/easy-rsa/pull/135 and https://github.com/OpenVPN/easy-rsa/issues/137.

Since the two tests using double brackets are not critical, I don't see much reason to address this on my side, other than updating easy-rsa as soon as a new release with the fix is out.

If a new release isn't out in a reasonable amount of time (v3.0.1 and v3.0.2 were separated by nearly two years), I will intervene and fix this on my side.

I'm leaving this open even if it's not an issue with my project itself, until a fix is deployed.

**Comment by Nyr** [comment]
I have deployed a fix on my end while this gets resolved upstream.
