### ISSUE TITLE
Script doesn't check to see if dpkg is locked

### ISSUE THREAD

**Issue by MisakaImoutoWaifu** [Nyr/openvpn-install#37]
The script assumes dpkg isn't locked and tries to work normally.

**Comment by Nyr** [comment]
You are right, but why should it check? We assume the user isn't installing other packages at the same time, which is common sense.

Am I maybe missing something else?

**Comment by MisakaImoutoWaifu** [comment]
Various reasons why someone might think dpkg isn't locked when it is. I had a broken connection at the end of an upgrade and I didn't realize dpkg was locked until I tried using your script to remove openvpn.
Before that it just seemed like the script was broken. 

Thank you for the script by the way, it works flawlessly otherwise.

**Comment by Nyr** [comment]
I understand your specific situation. From time to time, someone complains about missing error checking, and fact is it could be a lot better: from locks to input, existing installations or firewalls.

At the end of the day, I decided to implement only very basic error checking since it would take a lot of time to code and test as we add more complexity.
