### ISSUE TITLE
Link on Bandwagon Host doesnt work :)

### ISSUE THREAD

**Issue by antmak** [Nyr/openvpn-install#380]
```
Oops, there's a problem...
Out of Stock
```

**Comment by Pofilo** [comment]
Was it a sponsored link ?
If not, we should add at least 3-4 providers as an example !
If it was, it should be fix easily :)

**Comment by Nyr** [comment]
I was already aware but thank you. Will change it if stock doesn’t return.

@Pofilo it is an affiliate link, yeah. Outside of that, I considered maintaining a list of other cheap and reliable providers (not affiliates), maybe make a page using the wiki feature on GitHub... But honestly it would be a bit of a pain to maintain, it was like that years ago and half of the commits ended up being updates to the providers list, because offers often change or disappear.

I still think that choosing the right ISP is very important for those of us who use a VPN daily, and there is a lack of places where you can go and obtain unbiased recommendations of stable providers with a good network, etc... something should be done about it.
