### ISSUE TITLE
connect problem

### ISSUE THREAD

**Issue by pieterdorenbos** [Nyr/openvpn-install#385]
hey i have openvpn succesfully installed on my blazing fast vps server and it is all working good but when im trying to connect than i get this error https://gyazo.com/51274928b5d6aa43711425929c257c8d 
can someone help my with this

**Comment by Nyr** [comment]
Usually this means that there is a connectivity issue.

Maybe a firewall is interfering, the network could filtered, or a similar problem is happening. I suggest to try connecting from a different device and network, if that works you know where the problem is.

The issue is not with the script. Please use the OpenVPN forums if you need further assistance.

**Comment by pieterdorenbos** [comment]
we tested it from my friend his network aswell can it by the blazingfast his firewall

**Comment by Nyr** [comment]
As already said, the provided log usually means that there is a connectivity issue. If you have tested from a different device/network and is still happening, the problem could be on the other side or somewhere else, for example if you are connecting from a country where VPN traffic is targeted.

Please go to the OpenVPN forums if you need further help troubleshooting.

**Comment by pieterdorenbos** [comment]
werhe is the OpenVPN forums im new

**Comment by Nyr** [comment]
https://forums.openvpn.net/
