### ISSUE TITLE
add autolocal

### ISSUE THREAD

**Issue by gazialankus** [Nyr/openvpn-install#386]
May I suggest you add autolocal to this server config line?

`push "redirect-gateway autolocal def1 bypass-dhcp"`

I suffered here: https://askubuntu.com/a/983260/767823 and it seems I'm not the only one. 

Apart from that, thank you so much for this script!

**Comment by Nyr** [comment]
This will not be implemented, mainly because a road warrior setup never needs the `local` flag in normal circumstances, it is expected that you are always connecting to a server in the internet.

There are additional issues, since you may think that it could be added because it causes no harm: `autolocal` only works on Windows clients and I do not know if it could cause issues in some rare clients where it isn’t recognized (the official client simply ignores it in non-Windows, but others I have no idea).
