### ISSUE TITLE
failed to install

### ISSUE THREAD

**Issue by jiangjiucong** [Nyr/openvpn-install#387]
after running the script ,something wrong happened.(my VPS is provided by Virmach)here are some logs and screenshots i would show you ,would you like to help me?And i can't find the file:/root/jiang.ovpn .
![14](https://user-images.githubusercontent.com/33896683/33751996-c509deb4-dc19-11e7-8086-9eae1ece4dde.png)

**Comment by Nyr** [comment]
If you have previously installed Streisand or OpenVPN any other way, this could happen because of that. Try the script on a clean system, please.

Other than that and not related to this issue, please also note that OpenVPN will not work from China mainland, in case you are located there. I suggest to use Shadowsocks instead.

**Comment by Nyr** [comment]
I forgot: if your provider is using OpenVZ, #206 could also be the issue.
