### ISSUE TITLE
thx and small suggestion

### ISSUE THREAD

**Issue by aveeshkumar** [Nyr/openvpn-install#389]
Hello,

thx for your excellent script

I would like to suggest you to do either 
sudo systemctl status openvpn@server.service
or ask users to check it

Please do mention the 3 things needed for openvz instal (ubuntu 16.04) l:
- enable TUN
- comment out LIMITNPROC line in /lib/systemd/system/openvpn@.service
- systemctl daemon-reload
- sudo systemctl start openvpn@server.service

Verify using sudo systemctl status openvpn@server.service

**Comment by Nyr** [comment]
> I would like to suggest you to do either
> sudo systemctl status openvpn@server.service
> or ask users to check it

I don't think this is needed... if the service doesn't start, it'll inform the user.

> enable TUN

The script shows the following message if TUN is not ready: `The TUN device is not available.
You need to enable TUN before running this script`. It can't be more specific because depending on the platform, the procedure to enable TUN will be different.

> comment out LIMITNPROC line in /lib/systemd/system/openvpn@.service

This is not always needed, indeed it is only needed in rare occasions with container-based virtualization. The script doesn't modify the service file itself because that can't be a permanent solution and service file will be overwritten over time with updates. The solution is sadly in the hands of upstream devs who are aware of the issue and refuse to do anything about it. More broadly, I get the feeling that OpenVZ is becoming less prevalent over time so I get the impression that maintainers care less about this kind of issues than some years ago.

**Comment by aveeshkumar** [comment]
Hi,

Perhaps I was sleepy or had done too many re-installs that I didnt see the
message that service had not started

I guess it is a NOOB issue but it wont hurt to let the user know that they
should check the service status

Thank you for an excellent script - do get a coffee from my measly donation
- or chai :-)


Aveesh
--------------------------------------------------
Making Technology Work better

**Comment by Nyr** [comment]
Thank you :)

And it is not a "noob issue", the LimitNPROC thing needs to be addressed by those responsible. Multiple issues had been opened in their respective issue trackers and they just don't care, sadly.
