### ISSUE TITLE
Cannot make a openVPN server on Ubuntu 17.10

### ISSUE THREAD

**Issue by Moulick** [Nyr/openvpn-install#406]
I am able to create the VPN server on ubuntu 16.10 but not 17.10. The host is digitalocean.
The script installs the server and everything alright without any error on both. But I cannot connect to the server on ubuntu 17.10. I am using Port 53 if that matter.

**Comment by Nyr** [comment]
> I am using Port 53 if that matter.

It does. Your issue happens because systemd-resolved is enabled by default in Ubuntu 17.10 and it binds to port 53 UDP. Since systemd-resolved is already using that port, the OpenVPN service will fail to start.

If you don't need systemd-resolved but do want OpenVPN listening in port 53 UDP, it can be done:

```
systemctl stop systemd-resolved
systemctl disable systemd-resolved
service openvpn start
```

**Comment by Moulick** [comment]
Okay, thanks. Port 53 is would be the last port I would use but my hostel blocks all over ports except 53, 80, 443

**Comment by VBQL** [comment]
Use port 80 or 443 then

**Comment by Moulick** [comment]
Yeah, but am running nginx on the server and reverse proxying deluge so I need 80, 443 for that. No worries though. I am now back to 16.04 which works wonderfully. I wouldn't even need to proxy the UI of deluge if ports weren't blocked.
