### ISSUE TITLE
Using script to set up reverse client tunneling

### ISSUE THREAD

**Issue by GarrukApex** [Nyr/openvpn-install#411]
Hi Nyr,
I'm sorry if this isn't the right place for this, but I'm having a hard time getting help with my project, and I think part of it might be the script. I have several questions on numerous forums, but I'm having a hard time configuring the server. The point is to have it act as a link between two clients, so that I can tunnel my pc, through the vpn server, to another client node which had tunneled out back to the vpn. I explain it better [Here. ](https://unix.stackexchange.com/questions/420235/configuring-openvpn-server-for-reverse-client-tunneling) Anyways, sorry for bothering you with my problems. The client just throws this error when I try to connect. I haven't even gotten to setting up the gateway part (something I also don't know how to do) but it's getting a bit frustrating. 

Thanks. The errors I'm getting on the client side are below. 

`Mon Jan 29 17:57:55 2018 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Mon Jan 29 17:57:55 2018 TLS Error: TLS handshake failed
Mon Jan 29 17:57:55 2018 SIGUSR1[soft,tls-error] received, process restarting
Mon Jan 29 17:57:55 2018 Restart pause, 5 second(s)
Mon Jan 29 17:58:00 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]45.48.56.89:1194
Mon Jan 29 17:58:00 2018 Socket Buffers: R=[212992->212992] S=[212992->212992]
Mon Jan 29 17:58:00 2018 UDP link local: (not bound)
Mon Jan 29 17:58:00 2018 UDP link remote: [AF_INET]MYACTUALIP:1194
Mon Jan 29 17:58:00 2018 TLS: Initial packet from [AF_INET]MYACTUALIP. 1194, sid=f7f18e71 e1ce8d8e

`

**Comment by Nyr** [comment]
Okay, so this is definitively not related to my work but I'll try to chime in since you seem to have issues figuring it out.

There are multiple fronts here:

1. Your error log in Stack Exchange while trying to connect from the Pi Zero: easy, it is very likely a permissions issue. Multiple approaches to resolve this, but just try running with sudo and should work.

2. Your error log here: I assume that it happens trying to connect from your PC to the Pi 3. It is very likely a connectivity issue. I also assume that the Pi 3 is inside your network, if you are trying to connect to it via your public IP address, this could be causing it. Use the internal network while inside your network, use the external IP when outside. A router not correctly doing the NAT or even your domestic ISP filtering inbound connections could also cause this. You will need to troubleshoot those possibilities.

3. The routing to achieve what you want. If you want to use the Pi 0 as a gateway to the network it is connected to, this can be done, but it is far out of the scope of my work. Do some research on Linux networking since I don't really know what you exactly want. It is also possible that OpenVPN is not your best option for the drop box <-> server connection.

I hope that this helps, but if you need further assistance please do not seek it in this issue tracker.
