### ISSUE TITLE
IPV6

### ISSUE THREAD

**Issue by thedevly** [Nyr/openvpn-install#42]
Hello! Great work buddy ! But what about IPV6 ?
I'm using DO so they have IPV6, I think it will be AWESOME to have IPV6 with it.

**Comment by Nyr** [comment]
IPv6 support is a difficult matter. As much as I would love to add support for this, currently most IPv6 implementations are a mess and DigitalOcean is the perfect example.

OpenVPN, requires a subnet to support IPv6 natively. This isn't a problem with any decent IPv6 implementation which implies assigning at least a /64 routable subnet to each server. The problem is, many ISPs don't really understand IPv6 and do stupid things like assigning a single IPv6 to each server, which is what DigitalOcean does.

In the end, there are so many broken IPv6 implementations and problems with IPv6 (like the HE/Cogent stupidity), that at the moment is simply not possible to support this and make it work as it should.

Sorry, but it's simply not possible at this point.

**Comment by njb-said** [comment]
Has this been reported on digitaloceans feedback site? It's quite a critical issue really, in general not just for a vpn.
(As my ISP doesn't support IPv6 yet I can't really use IPv6 other than through a vpn, and therefore I can't build my sites to support it easily)
