### ISSUE TITLE
Feature Request: Bulk client creation

### ISSUE THREAD

**Issue by wicknet** [Nyr/openvpn-install#435]
@Nyr - For usability and sheer stability, your script to spin up a new OpenVPN server is in a class of its own. Thank you from a longtime and super-grateful user.

Exploring Pritunl, one feature that seemed fairly useful was its ability to bulk-create users in the dashboard, simply by typing (or pasting) a list of names and emails, one per line. 

As many folks spinning up VPN instances end up helping family and friends get privacy online, wondering if you might consider bulk user creation as a possible addition to your superb script, perhaps as a stand-alone shell command that reads a user-supplied text file and invokes the installer to run though it, generating user profiles to match? Although user creation works fine as is, it does get a bit tedious to run the same commands 10-15 times initially, while replacing the default client name each time.

FWIW. Thanks!!

**Comment by Nyr** [comment]
Thanks for your good words.

This feature is not planned for the script because I consider it a niche one, it's actually the first time that something like this has been requested.

That said, I see that you still need a solution for your very reasonable issue, as the current way clearly isn't optimal if you need to run the installer for lots of users.

So I've made a compromise and created [openvpn-useradd-bulk.sh](https://gist.github.com/Nyr/d032583897a2051a4b7e40f540a24e0f) for you. It should satisfy your needs and those of anyone wanting to set up lots of users after the initial setup.

**Comment by wicknet** [comment]
@Nyr - as always, your willingness to consider even outlier requests and then devote the time to speedily implement a solution is gratefully acknowledged. 

THANK YOU!!

**Comment by wh1ter0z** [comment]
hello this make user without password ?
