### ISSUE TITLE
Option to add username and password for user

### ISSUE THREAD

**Issue by sonu703** [Nyr/openvpn-install#44]
I need to add a user name and password for user to be able to connect instead of using the certificate. What changes are required?

**Comment by Nyr** [comment]
This is not an issue with the script and this will not be supported in the near future.

https://www.google.com/search?q=openvpn+username+password

**Comment by sonu703** [comment]
Can I avail your services to do some modifications in the script?
1. Ability to connect via user name and password. In built certificate to connect not required for my use case.
2. Ability for unlimited users to connect with same username and password.

I am willing to pay/donate. Let me know.

**Comment by Nyr** [comment]
Here you have the script modified to add the two features you requested:

- PAM authetication used instead of client certificates
- duplicate-cn to allow multiple connections per user

https://gist.github.com/Nyr/01717d9cf5db045e9520

This is only to satisfy your request and totally unmaintained/unsupported.

Pay/donate whatever you want.

**Comment by Nyr** [comment]
I was under the impression you would maybe "forget" to pay if I acted in good faith and provided the work first + allowed you to contribute as little as you felt was right for my time.

It doesn't surprise me I wasn't wrong after all and you didn't keep your word.
