### ISSUE TITLE
Feature request: 100% unattended install via command line parameters

### ISSUE THREAD

**Issue by dylanmtaylor** [Nyr/openvpn-install#452]
Let's say I want to cancel my VPS server when it's not needed or I'd like another IP address/location. I'd like to be able to very quickly spin up another one non-interactively. One provider that I use, Vultr, allows this via startup scripts. They also bill hourly and have $2.50/month KVM nodes. Simply put, I would like to be able to have a startup script with something like this:

```bash
yum update -y
wget https://git.io/vpn -O openvpn-install.sh && bash openvpn-install.sh --protocol udp --dns 1.1.1.1 --client dylan
```

It's not too hard to use the script now, but making it so it can be more automated would be nice

**Comment by Nyr** [comment]
This will not be implemented at this time.

The proper way for what you want would be to have one .opvn file generated with a dynamic host name configured and quickly deploy pre-existing certificates to a new server, maybe even start said server via the provider’s API. That’s out of the scope of this script, probably there is something already written for what you want using one of the modern configuration management systems (Puppet, Chef, Ansible...).

I understand that an unattended setup could still be useful sometimes, but this is not planed at this time.

For your use case I would suggest to deploy pre-existing certificates if you are serious about it, this will save the biggest amount of time since the rest of setup can be done in 5-10 seconds. Using dynamic DNS would also mean that you don’t need to reconfigure your client when server changes.

**Comment by Nyr** [comment]
You can also consider using Shadowsocks instead. This could be done in 10 lines of bash easily and you don’t need to deal with .ovpn files, just change the IP in the client.

Sorry for the multiple messages, I just kept thinking about this.
