### ISSUE TITLE
some minor issues

### ISSUE THREAD

**Issue by behzadba** [Nyr/openvpn-install#458]
This is very good but recently got some problems:
1. No option on where to save the final .ovpn file. I'd like it to be in the same folder that the script is located so I can easily have access to move it to more safe places. Right now /root folder is hard to reach. 

2. It does not give the flexibility of choosing key sizes and encryption method while older version had that feature. 

Thanks a lot for this awesome script by the way.

**Comment by Nyr** [comment]
1. The script defaults to the home directory for saving the `.ovpn` because that's statistically the place most likely to have write permissions and to be useful for the user. Unless someone comes with a better idea, this will likely not change, I don't like the idea of creating an additional prompt for this, sorry.
2. No version of this script has ever implemented those features, because the proper settings are already selected for the user. You are probably confused because 
a  copy  of  this  script  advertised by someone unrelated to this project cluelessly offers that choice. I say cluelessly because from OpenVPN 2.4 the cipher is negotiated except if negotiation is explicitly disabled, which he doesn't do.

I hope that this clarifies things a bit. I like to keep the script simple and user friendly, so advanced or niche features are not likely to be implemented.

**Comment by behzadba** [comment]
ok, now that I have you available, is it possible to quickly change the server ip after the installation? For me the server is at home so the ip changes once in a while, so I have to uninstall ovpn and start over to give it the new ip. Is it easy/possible to have an option for updating server IP?

**Comment by Nyr** [comment]
If your server is inside a private network, it is easy because its private IP address doesn't change, only the public IP address which is not directly exposed to the server. See #456 if this is your situation. In that case, you should probably use a dynamic DNS service to help with this.

If your server is directly exposed to the internet (without NAT) situation is a bit more complex because you need to update the server configuration, but there has been discussion on this issue tracker with some guidance about it if you are interested.
