### ISSUE TITLE
Setup on NAT VPS - Not working

### ISSUE THREAD

**Issue by Zyrexus** [Nyr/openvpn-install#468]
Hey, I set this up on my nat VPS and its not connecting from the client.
The ports and the IP is correct so IDK what's wrong.

IP Tables:
![image](https://user-images.githubusercontent.com/14060724/40269451-be3f6d6a-5b76-11e8-8166-aa794c20ef21.png)

![image](https://user-images.githubusercontent.com/14060724/40269391-ca40972a-5b75-11e8-8317-571fbdd4cab9.png)
![image](https://user-images.githubusercontent.com/14060724/40269410-00e370cc-5b76-11e8-93d7-4da8ed207919.png)
^ Inception hosting UK server NAT VPS - (hidden last 4 numbers on IP in case they still don't want it public)

I also tried my phone as well to see if its just my pc or something and it doesn't work as well as using 4g.

Thanks in advance,

**Comment by Nyr** [comment]
Everything looks good from here and you've done all the usual troubleshooting. Your detailed report is very useful to discard some of the most common issues, so thanks.

The error shown by the client is usually the result of connectivity problems between client and server, but given that you have tried from a different device and internet connection, it's weird.

Try the following:
- Run `netstat -ntlup | grep openvpn` in the server. OpenVPN should show there listening in your selected port. If nothing appears there, the installation somehow didn't complete successfully.
- Set up the server selecting TCP instead of UDP. Use a [port checker](https://www.yougetsignal.com/tools/open-ports/) to confirm that your port is open. If that's the case, you likely have some kind of issue in your client side.

If nothing of this helps, please use the the OpenVPN forums for further assistance, we try to help a little bit but this is issue tracker is not the right place to seek personal support.
