### ISSUE TITLE
DNS not working on local vpn connection

### ISSUE THREAD

**Issue by MSaadatt** [Nyr/openvpn-install#470]
Hi, I have a local DNS in the server, when I use OpenVPN on my public IP my local DNS that has been pushed to OpenVPN server configuration works fine, but when I change the remote line in my client OpenVPN configuration to the local address of the server connection established but my local DNS not working anymore:
Assume that my server public IP is: 66.66.66.66 (This is the IP what my client configuration generated by it), and my server local IP is: 192.168.0.110 when I change this line ``remote 66.66.66.66 1194`` in my client configuration file to ``remote 192.168.0.110 1194`` my local DNS not working but I can reach my services via IP address.

Can you help me to handle this problem?

**Comment by Nyr** [comment]
This issue is in no way related to the script and your explanation is not very clear to me.

I am not sure of what are you trying to achieve with a road warrior setup over a local network, but I suspect that it has nothing to do with the intended purpose of this script.

If that's the case, please seek help elsewhere.
