### ISSUE TITLE
Google Cloud issuse

### ISSUE THREAD

**Issue by Mehran** [Nyr/openvpn-install#471]
i run this script on both `DigitalOcean` and `Google Cloud` , on `DigitalOcean` it work well but in `Google Cloud` not work . am i should do something ? also 
```
netstat -ntlup | grep openvpn
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
```

**Comment by Nyr** [comment]
This is not a personal helpdesk to help you freeload bandwidth from free trials. It would be useful if instead of spamming multiple issues you provided something better than "not work".

Open the port as instructed in #462 and learn to set up the NAT in https://github.com/Nyr/openvpn-install/issues/138#issuecomment-196055353.
