### ISSUE TITLE
No internet connection on Virtual Bridge Interface

### ISSUE THREAD

**Issue by frednsiah** [Nyr/openvpn-install#490]
Hello,

I'm not able to get OpenVPN to work on my server box. I have a container on the box which has the OpenVPN script installed on it. I've bridged my network through virtual NICs which work perfectly. The container itself is assigned an ip of 10.1.10.1 through the host machine, and through the Virtual NICs bridge on the first interface, I've assigned a static private ip address of 192.168.1.201. Since the box has multiple NICs, I connected a cable from the second NIC directly to the ISP modem, created a Virtual NIC bridge from that NIC to the Container and assigned a static public ip (173.12.x.x) I can access the box using the static ip, private ip address (router/local network) and the other private ip address (through the host machine. Let me list it below to avoid any confusion.

1) Host machine assigned **10.1.10.1** to the container. I can access the container through the host machine.

2) Default NIC (br0) assigned through a virtual NIC (ens8) which map to a physical NIC. It is connected from a router and I've assigned a static local IP of **192.168.1.201**. I can assess the container when connected to the router.

3) Other NIC (br1) assigned through a virtual NIC (ens9) which maps to a physical NIC. It is connected directly from the ISP modem. I've assigned a static remote IP of **173.12.x.x**. I can access the container anywhere.

Connecting to OpenVPN works, but there is no internet connection. Below is my iptables -L -t nat:
```
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
SNAT       all  --  10.8.0.0/24         !10.8.0.0/24          to:173.12.x.x
```

Any help will be greatly appreciated, thanks.

**Comment by Nyr** [comment]
The issue is obvious, NAT from the server to the internet is not working.

Since you have inbound connectivity working as you want, the question would be: how do you want to exit to the internet from the OpenVPN tunnel? If the answer to that is the NIC which has `173.12.x.x` available, your issue is not with the script configuration but elsewhere in your networking. If you instead want to exit through one of the local IP addresses which has internet connectivity via NAT, that's possible but then you have the server-side NAT set up incorrectly since the SNAT should forward to that IP address.

I think that the first situation is the most likely in your case. If that's it, I can't really help, that's an issue somewhere else with your networking.
