### ISSUE TITLE
Undefined behaviour due to unlimited --port range

### ISSUE THREAD

**Issue by TinCanTech** [Nyr/openvpn-install#501]
This script allows for out of bounds Port to be selected.
eg: 0 -> 66666 (and more)

Port 0 results in undefined behaviour within Openvpn and should be disallowed.
Port 65536+ should be disallowed.

I would imagine that no port below 20 would be an acceptable policy.

Source:
https://forums.openvpn.net/viewtopic.php?f=1&t=26860

**Comment by Nyr** [comment]
The script doesn't do input validation at all.

In your linked thread, the user simply censored port number and public IP address. You can see that he shows port `0000` in the server while client is `000`. From the client connection log, it doesn't look like he has a connectivity issue, but the TUN driver is having issues instead. So that's exactly the kind of issue which has nothing to do with the script and I was talking about in #491.

**Comment by TinCanTech** [comment]
> The script doesn't do input validation at all

Ah .. well, then I re-affirm my statement that Openvpn will not support your script.
