### ISSUE TITLE
Extremely slow speed caused by the use of SHA512

### ISSUE THREAD

**Issue by nedis4** [Nyr/openvpn-install#527]
Firstly, thanks to developers for this script!
But why does it generate config that uses SHA512 auth instead of default SHA1? It caused _extremely_ slow speeds for me on both 120mpbs and 5mpbs connections and I had to spend 2 hours trying to figure out what's wrong (not a network guy).
I think most people would like to see the script use SHA1 by default.

**Comment by Nyr** [comment]
> But why does it generate config that uses SHA512 auth instead of default SHA1?

Because SHA1 is broken and SHA512 isn't.

Anyway I doubt that this configuration setting is responsible for your slow connection speeds. Indeed, if you are using an AEAD cipher (both client and server running OpenVPN v2.4+) the `--auth` parameter is ignored for the data channel and only used for the control channel which transmits very little data in comparison.
