### ISSUE TITLE
Password.

### ISSUE THREAD

**Issue by t0nic** [Nyr/openvpn-install#529]
Hey, Nice script! I was manually installing openvpn and decided midway to check for an auto installer, and found yours. (top of google)  <--- wew

I've got one concern, how do we add a password for the user? If you explain where it needs to be modified I can add it to the script for you, I am just not sure where it goes.

**Comment by Nyr** [comment]
There are two lines in the script which contain the following string:

`EASYRSA_CERT_EXPIRE=3650 ./easyrsa build-client-full $CLIENT nopass`

Remove the `nopass` parameter and you'll then get an interactive prompt for the password during user creation.

**Comment by Bleuzen** [comment]
It would be nice to be able to add a client with password without modifying the script.
The solution of @ShevT looks good.
Another way would be to just remove the nopass and print a message telling the user he/she can pass 'nopass' to disable password.

**Comment by Nyr** [comment]
Certificates with password are not planned at this time. In most cases, if the certificate is compromised, the password could be too.

**Comment by Bleuzen** [comment]
Could, yeah. But in most cases not.

For example when I lose my phone with the unencrypted ovpn file on it: the ovpn file is there, unencrypted, nothing to enter to use it. This is bad.
If there would be a password, I would be safe, without having to run home and disable this client, which is not possible in some situations.

Another case would be malware, which steals data. Again, if the ovpn needs no password, anyone can use it.

Just because someone got the ovpn file (which could happen in many ways somehow)
this doesn't mean this person also has the password.
Thats why I think to have a password on such files is very important.

**Comment by Nyr** [comment]
The malware situation was exactly what I was referring to. If the the system is compromised, it's game over regardless of the password.

I can understand that there are some cases where this could be useful, but in my opinion there aren't many and this will not be officially supported for now, sorry.
