### ISSUE TITLE
Would it be better to use ffdhe4096 instead of generating one?

### ISSUE THREAD

**Issue by bryceml** [Nyr/openvpn-install#532]
https://wiki.mozilla.org/Security/Server_Side_TLS#Pre-defined_DHE_groups says that it is best to use pre-defined dhe params.  This would give a speed improvement to the installation, especially on low end devices.  It would supposedly also be safer.  Is there a reason not to do this?

**Comment by Nyr** [comment]
Using a 4096 bit DH with the current 2048 keys wouldn't make much sense in my opinion. I've been reading some hours on this matter and ffdhe2048 has now been implemented, thanks for the suggestion.

Using your own, uniquely generated, 2048 bit DH is very likely safer in the real world because your unique DH parameters will never be interesting enough for an adversary to break (I hope). But this is a good compromise for a faster setup.
