### ISSUE TITLE
Support for IPv6?

### ISSUE THREAD

**Issue by fakefortemp** [Nyr/openvpn-install#534]
I changed protocol from udp to udp6 (both server and client) and IP address from IPv4 to IPv6, but it didn't work. Is there anything else that I should be concerned about?

**Comment by Raideerke** [comment]
Probably know the anwser for this.
As of the https://github.com/Nyr/openvpn-install/issues/497 topic, ipv6 isnt't supported by the script, but OpenVPN does support, so you can configure following @Nyr 's anwser written in the https://github.com/Nyr/openvpn-install/issues/502 issue ticket to use ipv6. 

Hope it helps.

**Comment by Nyr** [comment]
Your answer is in #497, thanks @Raideerke.

**Comment by bryceml** [comment]
I'll add here what I do to enable IPv6 since it takes a bit of reading elsewhere to figure it out.

If you want to reach the vpn over ipv6, the only thing you have to do is change `proto udp` to `proto udp6` in server.conf which makes it dual-stack and make sure the remote line for your client is either pointing to a dual-stack dns address, or an ipv6 address so it looks like `remote dualstack.example.com 1194`.

If you want your vpn to carry ipv6 traffic, just add `server-ipv6 xxxx:xxxx:xxxx:xxxx::/64` and `push "route-ipv6 2000::/3"` to your server.conf where the server-ipv6 address is a range of addresses that is routed to your vpn server.  You will also need to add `net.ipv6.conf.all.forwarding=2` to /etc/sysctl.conf.  In the case you can't route a public ipv6 prefix to your server, you could use ipv6 nat with unique local addresses for the vpn or neighbor discovery proxy but those are less than ideal ways to do it.

**Comment by fakefortemp** [comment]
> I'll add here what I do to enable IPv6 since it takes a bit of reading elsewhere to figure it out.
> 
> If you want to reach the vpn over ipv6, the only thing you have to do is change `proto udp` to `proto udp6` in server.conf which makes it dual-stack and make sure the remote line for your client is either pointing to a dual-stack dns address, or an ipv6 address so it looks like `remote dualstack.example.com 1194`.
> 
> If you want your vpn to carry ipv6 traffic, just add `server-ipv6 xxxx:xxxx:xxxx:xxxx::/64` and `push "route-ipv6 2000::/3"` to your server.conf where the server-ipv6 address is a range of addresses that is routed to your vpn server. You will also need to add `net.ipv6.conf.all.forwarding=2` to /etc/sysctl.conf. In the case you can't route a public ipv6 prefix to your server, you could use ipv6 nat with unique local addresses for the vpn or neighbor discovery proxy but those are less than ideal ways to do it.

Thanks a lot! The first solution is just what I need.
