### ISSUE TITLE
fedora 29 (and probably other distributions) expect another path for server.conf

### ISSUE THREAD

**Issue by bedawi** [Nyr/openvpn-install#536]
Hi there!

First: Thanks for your work, your script does a wonderful job!

One issue I found is that the script creates all config files in /etc/openvpn/. This leads to problems when using fedora 29, where the files are expected in /etc/openvpn/server

**Comment by Nyr** [comment]
Thanks for the report.

I was not aware of Fedora specifically, but other distros are also transitioning to this new directory structure. Fedora isn't officially supported, but the change can/will probably come downstream to CentOS.

I did actually write a patch to address this more than a year ago, it is a bit more complex than locating the right path, because there are new services and stuff, at least in other distros. The patch wasn't merged at the time because the old structure was still fully supported.

I am keeping this issue open to address it before it becomes a problem in CentOS.

**Comment by Nyr** [comment]
This has been addressed in a46a23d84a4b007dc8f6e964219331f876a21602.

Installing in Fedora mostly works now, except SELinux compatibility which will probably be resolved in the near future.

Still, Fedora is officially unsupported for now and no guarantees are provided.
