### ISSUE TITLE
Cannot connect to openvpn

### ISSUE THREAD

**Issue by sadra** [Nyr/openvpn-install#545]
Unfortunately, I can't connect to server!

The TunnelBlink always stock on "Waiting for response"!
What should I do? Is there any needed configuration on my server?

My server is Ubuntu 18.4 From Hetzner.cloud

**Comment by Nyr** [comment]
Your government is blocking OpenVPN connections.

I suggest to use Shadowsocks instead, that will work.

**Comment by sadra** [comment]
> Your government is blocking OpenVPN connections.
> 
> I suggest to use Shadowsocks instead, that will work.

Oh no, that's not true!

I'm using this script on another server at Germany and USA too, and they work fine.
But I'm not successful to connect the Hetzner's server, so I want to know is there any special configs for the server that I should pay attention to them?

**Comment by Nyr** [comment]
I am surprised that you can connect to OpenVPN servers set up by my script from Iran, but of course you will know the situation better than me. Last I heard, OpenVPN was mostly filtered but usable with obfuscation.

That said, this is a tracker for issues with the script, not a support forum. I still suspect that your VPN connection to that specific server could be filtered even if others aren't, specially since you already seem to have experience using my script and Hetzner doesn't have a cloud firewall which could interfere.

**Comment by mehranexpert** [comment]
i also try your script From Iran in server VPS , DigitalOcean , Azure , Uplcloud , it Connect but no Internet .

**Comment by anuragbhatia** [comment]
Can you share trace to any popular website after connecting the VPN? Would be interesting to see the trace.

**Comment by mehranexpert** [comment]
@angrysnarl  after connect to VPN , not any site opened , i aslo try Ping but  Time-out . i check NAT and IPTABLES seems everything is okey .

**Comment by Nyr** [comment]
@mehranexpert your case seems to be different because you can connect to the server, while OP can't.

If your server is behind NAT, see this: https://github.com/Nyr/openvpn-install/issues/138#issuecomment-196055353

Maybe, your connection is filtered even if you can initially establish to the server. As already said, OpenVPN is not the best tool to evade censorship.

**Comment by mehranexpert** [comment]
@Nyr Thanks for you reply . What about obfsproxy  ? can i use this script with obfsproxy Option ?

**Comment by Nyr** [comment]
@mehranexpert you can try, but again I don't know about the feasibility of Obfsproxy in Iran.

**Comment by DonZheng** [comment]
@Nyr,

Would you please consider adding Obfsproxy option in your great script? I am sure there is outcry in many parts of the world for it.

**Comment by Nyr** [comment]
@DonZheng https://github.com/Nyr/openvpn-install/issues/570#issuecomment-453584064
