### ISSUE TITLE
ip leak !

### ISSUE THREAD

**Issue by SeBL4RD** [Nyr/openvpn-install#546]

**Comment by SeBL4RD** [comment]
Hi Nyr,

I've been following your shell script for openvpn for a while and I've seen several problems.

First the RSA key that your script generated seemed to me that generate very quickly ... It is actually in 256 bit ??? 2048 bit would not be much more secure ?? the 256 bit is bruteforceable easily ...

And secondly this way of using it, don't know why, do not hide ip, there's ip leaks !!!! try this: https://ipleak.net/
I use a plugin on my browser to block webRTC ip leaks. But nothing works, there are clearly leaks ip ... The site also allows to test its ip leaks with torrents, the still there is a leak ip ...
I tested everything on own installations, openvpn on a clean debian VPS, also client side.

Third, could you add a choice to your script to uninstall it cleanly once the script has been started a second time?


Cordialement.


SeBL4RD

**Comment by kevin01523** [comment]
you can run the script once again to uninstall openvpn.whih i did to reinstall openvpn and upgrade to latest version hmm theres no ipleak on mine tho since it sends setnv block outside dns you can modify the client ovpn for that thoogh

**Comment by Nyr** [comment]
Given that you clearly lack even basic technical understanding on how the cryptography in OpenVPN works, I would please request that you refrain from discussing the security choices of this project.

To clarify, you are mixing up the RSA key, the DH parameters and the data channel cypher, which have different functions, different lenghts and do different stuff.

If your public IP address is leaking, that is a client issue and not caused by this script.

The uninstall feature which you request is already available as mentioned by Kevin.

**Comment by Nyr** [comment]
There are two types of common leaks, WebRTC and DNS. Both of them need to be resolved client side, they are not caused by the script.

A way of avoiding WebRTC in the web browser is using an extension like you did or completely disabling WebRTC.

For DNS leaks, you need to make sure that your client uses the DNS servers pushed by the server and not the ones previously configured in your computer. There is plenty of documentation in the internet about this.

**Comment by SeBL4RD** [comment]
Yes, I know, that's why I came back because my leak did not come from one or the other ... I just found the solution ... It was a leak of ipv6, openvpn can not hide ipv6 without us being forced to disable ipv6 on windows?

**Comment by Nyr** [comment]
You can remove the IPv6 default route only while connected to the VPN.

There are multiple approaches for this and clients which will do it for you automatically. For example I use Viscosity, which has an option for that.

**Comment by SeBL4RD** [comment]
It seems that in the end it does not come from there. Several sites tell me that I have a "transparent proxy", I do not understand why. 
All is ok except that,
 no DNS found, ipv6 or leaks with webRTC.

**Comment by Nyr** [comment]
> Several sites tell me that I have a "transparent proxy", I do not understand why.

Without going into details, that is perfectly fine. Transparent proxy means that the proxy, isn't leaking your public IP address. You are not using a proxy, but they don't know that.

**Comment by SeBL4RD** [comment]
Yeah, but lot of websites find my real ip x)

**Comment by SeBL4RD** [comment]
![screenshot_3](https://user-images.githubusercontent.com/45276149/48960271-5d42d400-ef6b-11e8-9b3a-159d9c753feb.jpg)

**Comment by SeBL4RD** [comment]
Ok, i will try on another computer, thanks.

**Comment by tabi** [comment]
![zrzut ekranu 2018-11-25 o 20 56 12](https://user-images.githubusercontent.com/67523/48983872-9f4b5180-f0f4-11e8-87c5-86dcd4cbb732.png)

This is what i've note after connecting through OpenVPN. What does it mean? leaking or not?

**Comment by Nyr** [comment]
@tabi how could I know?

If you are using CloudFlare DNS in your server but not the client, it's not leaking.

If you are using CloudFlare DNS in your client but not the server, it's leaking.

**Comment by SeBL4RD** [comment]
Hey Nyr, I definitely found the problem on my side, it was due to "Connectify Dispatch". A software that I use to mix 2 connections and have more flow with 4g and ADSL... It activates a value in the registry that does not remove even once the software closed, and even without my 4g it had that effect! I hope this discussion can help others. Thank you again for all.

Amicalement
