### ISSUE TITLE
Please handle expired certs, or offer to regenerate

### ISSUE THREAD

**Issue by AndKe** [Nyr/openvpn-install#558]
I am getting: ovpn-server[1400]: 193.156.110.130:44103 VERIFY ERROR: depth=0, error=CRL has expired:

So now I am looking how to regenerate/renew them.
It would be very nice if openvpn-install sound check expiration, and offer to fix it.

**Comment by AndKe** [comment]
I found solution in this post;
https://github.com/Nyr/openvpn-install/issues/453#issuecomment-384258306

having a menuitem that could check certificate expiration dates, and offer to renew, would be great.

**Comment by Nyr** [comment]
Please note that your issue is with a certificate revocation list, not a certificate per se.

That said, the script uses a very long expiration time for both the CRL and the certificates: 10 years.

This can be verified by using the following command and looking at the `Next Update` field:
`openssl crl -in /etc/openvpn/crl.pem -text`

The most likely reason for your issue is that either you regenerated the CRL manually or you are using a very old version of the script.

**Comment by AndKe** [comment]
yes, I guess it was about 4 or 5 years ago I discovered your shellscript.
Thank you.
