### ISSUE TITLE
blocked vpn in my country

### ISSUE THREAD

**Issue by hiphusk** [Nyr/openvpn-install#570]
Hi, I have a problem/request

## Issue
My government have implemented [Deep Packet inspection](https://en.m.wikipedia.org/wiki/Deep_packet_inspection) and blocked VPN connections, I cannot connect to my VPN server (unless there are heavy load on my ISP provider in the busy hours of the day then It might connects), 

## My Situation 
I really need VPN because my provider monitors my traffic, throttles some website and blocks news sites and others, this traffic data could be used against me to imprison me, for the time being I'm using tor but i can't use it on every program plus it's slow and impractical to use for work, I'd really appropriate your help.

## Request
is it possible to update the script so it implements optional OBFSPROXY, or in another script ?
I'm not the only one who is complaining with this issue, see [https://en.m.wikipedia.org/wiki/VPN_blocking ](https://en.m.wikipedia.org/wiki/VPN_blocking ) for more.

**Comment by Nyr** [comment]
It is unlikely that Obfsproxy will be implemented into the script.

That is because the best way to evade censorship varies from country to country and it is a cat and mouse game, what works today maybe will need to be upgraded tomorrow. I can't commit to support that.

But you have some options:
- Set up OpenVPN with protocol TCP using my script and configure Obfsproxy in the server by yourself. This is relatively easy and I am sure you can find a lot of guides if you need help. In the client I suggest that you try Viscosity, which includes Obfsproxy support.
- Use Shadowsocks. It is not a VPN but will tunnel almost everything since it supports both TCP and UDP traffic. shadowsocks-libev is very easy to set up in a server, but I am not 100% sure that it will work for you Iran.

I hope this helps.
