### ISSUE TITLE
ValueError: Port udp/53 already defined

### ISSUE THREAD

**Issue by MWalid** [Nyr/openvpn-install#582]
Hello,

I tried to install OpenVPN with port 53 / UDP it gave me the error:
```
ValueError: Port udp/53 already defined
```
Thank you

**Comment by Nyr** [comment]
The command which is failing is:
`semanage port -a -t openvpn_port_t -p udp 53`

Why? Because a different service (a DNS server?) is already configured with SELinux for that port and protocol. That's something which you need to resolve, the script has likely installed OpenVPN successfully (other than that).

**Comment by MWalid** [comment]
Thank you for the hint,

I tried the following command,
```
semanage port -m -t openvpn_port_t -p udp 53
```
Then reinstalled openvpn, tried to connect with the new configuration but got the error:
```
TCP/UDP: Incoming packet rejected from [AF_INET]8.8.8.8:53[2], expected peer address: [AF_INET]************:53 (allow this incoming source address/port by removing --remote or adding --float)
```
Any idea?

**Comment by Nyr** [comment]
It is always better for getting some context if you paste more than one line of logs, because initially I know nothing of your setup and can only make a guess. Also, if you censor your IP address, some context is lost.

Anyway in this case the explanation is kind clear, but not the cause:
- Client initially connects to ************:53
- Client then gets packets from 8.8.8.8:53 and rejects them because that's not the address specified in the `--remote` parameter.

Why does this happen? Something is wrong in your client network, I have no idea. Maybe your router or your ISP is hijacking all udp/53 traffic. Try using a different port and/or protocol. What country are you connecting from?

**Comment by MWalid** [comment]
Thank you @Nyr for your response,

Actually it works with almost any other port, I'm on public WiFi so maybe it's an issue with the router,

Will try later on from different router, will paste full logs here.

Thanks again.

**Comment by Nyr** [comment]
The public Wi-Fi is almost certainly hijacking DNS traffic, that is very common. I suggest to try TCP 443 if you want to try.

**Comment by MWalid** [comment]
I tried TCP 443 before, it didn't work either, I believe it's my ISP blocking it. I don't have any idea how they can do it since it's the standard https port.

**Comment by Nyr** [comment]
It is the HTTPS port, but OpenVPN traffic looks different than HTTPS for the trained eye (and for the trained firewall, of course).

**Comment by MWalid** [comment]
Yes they do have the best firewall around -- DXB
