### ISSUE TITLE
Add Support for AWS EC2 Amazon AMI 2?

### ISSUE THREAD

**Issue by ik1ne** [Nyr/openvpn-install#593]
Hi, I tried to use this on Amazon Linux 2 AMI, but it echoed "Looks like you aren't running this installer on Debian, Ubuntu or CentOS" and just quitted.

However, I managed to copypaste huge portion of the install part of the script and it worked fine.

So, I'm planning to fork this project, implement AWS EC2 Amazon managed AMI support, and create a pull request.

Thereby I'm opening this issue for work plan summary:

Plan

1. Add Amazon Linux 2 AMI detection part by using `curl 169.254.169.254/meta-data/latest/...`
   169.254.169.254 is used as [AWS EC2 metadata server](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html), so the script can read its `ami-id`, for `$aws ec2 describe-images --image-id=AMI_ID_HERE` which will return the detailed info of its AMI . If it is description is `Amazon Linux 2 AMI 2.*`, I think it's safe to say this script is being run on Amazon Linux 2 AMI image.

2. Replace easy-rsa package installation from wget build to [AWS EPEL repo](https://aws.amazon.com/premiumsupport/knowledge-center/ec2-enable-epel/).
`sudo yum-config-manager --enable epel` will add AWS managed EPEL repo, which means it will be managed by AWS, so I think using that will have probably less chance of failure than building it manually and get updates from AWS.

3. Fill NAT public IP question's default text to `public-ip`
Like plan 1, ec2 instances can get its `public-ip`, `private-ip` from its meta-data.

Well... actually this is my first time using github contribution, so tell me if this Issue has something problematic, like asking too much in one issue or something like that.

**Comment by Nyr** [comment]
Amazon Linux support has already been discussed in previous issues, although no one proposed your detailed approach.

Responding to your points:
1. I had been told that the script itself works in Amazon Linux. In theory, you would only need to edit the [OS test](https://github.com/Nyr/openvpn-install/blob/master/openvpn-install.sh#L29) to check for `/etc/os-release`. There is no need to add a new detection method for Amazon. The reason why Amazon Linux is officially unsupported was because I didn't want to commit support for a privative fork which requires me as the maintainer to be an Amazon customer. Yes, Amazon Linux is not privative de jure since the source code is available, but that's useless in practice. You also need to consider that Amazon Linux is a niche distribution, for example Arch Linux and even Fedora aren't supported at this time. I just don't want to commit support for small distributions, it is a lot of effort over time.
2. Then I would need to support whatever easy-rsa version the EPEL repo is carrying, duplicating the amount of work. New easy-rsa versions sometimes break thinks, that would also complicate the effort. Supporting a single, well known and modern easy-rsa version seems like the better choice to me.
3. While useful for Amazon users, then someone would want support for the Vultr API, others would want DigitalOcean, etc... my work is platform agnostic and again, I don't want to depend on platform specific stuff if possible.

I hope this explains my position.
