### ISSUE TITLE
Won't work with extra IP

### ISSUE THREAD

**Issue by Xairoo** [Nyr/openvpn-install#603]
Hi,

TLS will fail if I set an extra IP (should be the external IP for the vpn server) within the setup. For example the IP of eth0:1.

Running Debian 9.

Adding `local <extra_ip>` to the server.conf fixed it.

Cheers

**Comment by Nyr** [comment]
The default script configuration will make OpenVPN bind to 0.0.0.0.

Your change would make OpenVPN bind to your specific `extra_ip` only.

So I don't understand how could that fix anything.

**Comment by hwdsl2** [comment]
I think this use case is for servers with multiple external IPs. During setup, the script asks:
```
First, provide the IPv4 address of the network interface you want OpenVPN
listening to.
```
And the user can choose one of the extra IPs on this server as a response. Therefore it makes sense to add to `server.conf` the line mentioned in the original comment, to make OpenVPN listen only on this IP:
```
local <extra_ip>
```
If we don't do this, and the user respond to the question above using an extra IP that is not the main IP of the server, the user will not be able to connect using OpenVPN client, and the server will log these errors (you can reproduce this using a server that has multiple IPs and choose a non-main IP in the question above):
```
Sep 22 03:01:20 myhost ovpn-server[XXX]: X.X.X.X:XXX TLS Error: incoming packet authentication failed from [AF_INET]X.X.X.X:XXX
Sep 22 03:01:21 myhost ovpn-server[XXX]: X.X.X.X:XXX  TLS: Initial packet from [AF_INET]X.X.X.X:XXX, sid=XXXXXXXX XXXXXXXX
Sep 22 03:01:22 myhost ovpn-server[XXX]: X.X.X.X:XXX  Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #1 / time = (1569135681) Sun Sep 22 03:01:21 2019 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
```

I suggest that we add this `local` line mentioned above to the `server.conf` in the script.

**Comment by TinCanTech** [comment]
@hwdsl2 the error in the log you posted has nothing to do with which IP your server listens on.

For the vast majority of users of this script, having openvpn bind to 0.0.0.0 is the most sensible approach.  

For more advanced users, who's servers are multi-homed, openvpn has the option --multihome, which could be added to the config if --local is not used.

**Comment by Nyr** [comment]
Well, the problem itself exists, but it doesn't have anything to do with tls-auth.

I see two options:
- Detect multihomed servers and configure adequately
- Bind to the IP address specified by the user during setup

Adding to the injury, the message presented to the user when asked about the IP address is confusing and doesn't correctly explain what really happens (bind to 0.0.0.0, clients connect to the user-specified specified IP address).

An additional issue is that using `--local` would prevent the server from listening on IPv6 (I think) because OpenVPN doesn't support (yet) multiple `--local` parameters. This is something to consider in the future when I get IPv6 support into the script (but not very important because the tunnel can still carry IPv6).

Thanks for the report. I will add `--local` to fix this issue very soon.

**Comment by TinCanTech** [comment]
@Nyr multiple `listen` methods are in the pipeline.

**Comment by Nyr** [comment]
@TinCanTech I've seen the tracker, yeah.

The absence isn't a big issue for me because I'll implement IPv6 inside the tunnel but for now, no need for IPv6 transport.

**Comment by Nyr** [comment]
This has been addressed, thanks a lot for the report.
