### ISSUE TITLE
TCP can connect, but no internet access

### ISSUE THREAD

**Issue by xuancong84** [Nyr/openvpn-install#605]
For the latest versions, if you use TCP protocol, you can connect to VPN successfully, but you cannot access internet, probably a bug?
You can create a free-tier AWS instance and setup TCP VPN from raw scratch, it just does not work. Other Github repositories such as https://github.com/angristan/openvpn-install also ceased to work since a few months ago.

**Comment by Nyr** [comment]
Nothing changed in the script for this to stop working.

Additionally, there is no difference in how the forwarding is set up depending on protocol choice.

If you are trying to connect from a censored network (China), that could be the issue. If not, most likely there is something wrong in your side, not the script or AWS.

**Comment by xuancong84** [comment]
You do not need anything to be changed for the script to stop working, it could be due to the upgrade of some dependencies that makes your scripts deprecated and stop working.

FYI, I am not trying to connect from a censored network such as in China. And I have explicitly tested using "nc -l port" and "nc host-ip port" that the TCP port is indeed working.

**Comment by Nyr** [comment]
I understand that, but the report is very weird because:
- No one else has reported this and AWS is a very popular provider
- No recent changes relevant to the script in any of the supported distributions (to my knowledge)

I have no problem trying to reproduce/troubleshoot this if some change in AWS side is really causing trouble with the script, but it is very unlikely situation. A problem elsewhere is way more likely.

If someone else reports this issue, I will set up an EC2 instance and investigate.

**Comment by xuancong84** [comment]
Thanks for your consideration!
The reason why no one has reported I guess is because:
- It is quite recent. A few months ago, last September/October, I could still use it in TCP mode.
- Most people uses the default UDP protocol, so they will not encounter any problem.
- The problem is unlikely due to your script, because previously most Github OpenVPN scripts works, only recently all Github OpenVPN scripts stop working. So it has to be due to the upgrade of certain dependency packages such as openvpn or easy-rsa, etc., which breaks all Github OpenVPN scripts such as yours.

**Comment by TinCanTech** [comment]
@xuancong84  Do you know **exactly** what is broken ?

**Comment by h0wXD** [comment]
Having same issue here routing isn't working on either scripts on Ubuntu 16.04 / 18.04 neither TCP or UDP. Tried either image on AWS; allowed UDP 1194 / TCP 443 in security settomgs, It can connect successfully but routing won't work. Don't seem to be able to get any response from anywhere. I know my client openvpn is not broken as it works just fine with other openvpn servers.

**Comment by h0wXD** [comment]
FYI for anyone having same issue; I did not find a fix for this script but found out that https://github.com/angristan/openvpn-install does work for either TCP / UDP.

**Comment by Nyr** [comment]
@h0wXD your issue is not related to the OP. The most likely explanation for you is that the NAT wasn't set up correctly, learn how to do that here: https://github.com/Nyr/openvpn-install/issues/138#issuecomment-196055353

The repo you linked is just a fork of this one, which is the original. A low quality fork, if you ask me.

**Comment by ToshipSo** [comment]
Even I'm facing the same issue. I'm able to connect to the server using TCP protocol but can't access the internet. By the way, I'm using LetsCloud VPS.

**Comment by IosSos** [comment]
sudo iptables -t nat -A POSTROUTING -j MASQUERADE 
this is the solution, in the script it isn't present the Iptables rules

**Comment by Nyr** [comment]
@IosSos that is only needed if you have a dynamic IP address, or if your server is behind NAT and you selected a wrong configuration during setup. Unrelated to OP.
