### ISSUE TITLE
routing issues after apt upgrade

### ISSUE THREAD

**Issue by gregology** [Nyr/openvpn-install#609]
I'm running an Open VPN server on GCP (Ubuntu 18.04) using this script. It's awesome and has saved me loads of time. However, when I run an `sudo apt update && sudo apt upgrade -y` on the VPN server, the connected clients can no longer ping anything except the VPN server. The clients still can connect and ping `10.8.0.1` but that's all. This has happened a few times, each time I upgrade the server I have to `Remove OpenVPN` and then re run `bash openvpn-install.sh` creating users from scratch. 

Is anyone else having this issue and know how to rectify it?

**Comment by NextGenerationcloud** [comment]
Yes this is new Oo!

it does not work anymore
single subnet 149.171.90
See this server1 149.171.91
and
See this server2 149.17192
can reach -.-

**Comment by Nyr** [comment]
Thanks for the report.

It would help to know which packages where upgraded when this happened, but I think I may know what the issue is anyway. If someone can provide the output of the following commands before and after the conflicting upgrade, that would be helpful:
`ls -l /etc/rc.local`
`cat /etc/rc.local`

I am a bit busy but will do my best to get this resolved during this week, there was a planned commit which will likely fix this.

**Comment by gregology** [comment]
I'll do this on my next upgrade however that might be a couple of weeks away. Rolling the machine creds takes me a while so I need to find some free cycles :D

**Comment by haihoang20** [comment]
I'm seeing the same symptoms when using this script on a newly spun AWS instance (Ubuntu 18.04).

Steps:
1. Launch Ubuntu Server 18.04 LTS (HVM), SSD Volume Type
2. SSH into instance and run the the script `sudo sh -c 'wget https://git.io/vpn -O openvpn-install.sh && bash openvpn-install.sh'`
3. Connect to the VPN
4. Can't do anything but `ping 10.8.0.1`

**Comment by topcheer** [comment]
Is your internal IP address get changed if you are on AWS or GCP? cross check IP address with iptables NAT settings

Using "ip addr" to find out IP address of your ethernet interface

then 
    grep “your ip address” /etc/rc.local 

to see if there is any output, if not, then you are in trouble

find a line in /etc/rc.local similar as below

iptables -t nat -A POSTROUTING -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to 172.31.11.7

replace 172.31.11.7 with your real IP address

test this settings by doing

iptables -t nat -F
iptables -t nat -A POSTROUTING -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to "your real IP address"

if everything works, then you are good,

If you IP address get change every time after server reboot, then you will need to do the same every time

**Comment by Nyr** [comment]
@haihoang20 sorry for the late reply but I missed your message. Your issue isn't the same, see here for how to fix it: https://github.com/Nyr/openvpn-install/issues/138#issuecomment-196055353

**Comment by Nyr** [comment]
@gregology I checked this and am unable to reproduce. Can you ping 8.8.8.8 while connected to the VPN?

I am unfamiliar with GCP, but I suspect the problem could be related to the DNS.

- Compute Engine assigns internal DNS to the server, which can't be used from the VPN because the client has no route to them.
- By default (option 1) my script will select the internal DNS, which will not work from the VPN. Use any other option like 1.1.1.1 for example.

**Comment by gregology** [comment]
Hey @Nyr, sorry I haven't had time to run an upgrade and run

`ls -l /etc/rc.local`
`cat /etc/rc.local`

before and after. Next time I upgrade I'll run this as you suggest and ping the results here. Thanks again for your awesome script!

**Comment by Nyr** [comment]
Forget about the `rc.local` commands, a considerable upgrade was commited to the repo today which makes them deprecated. If there was a problem with that (although very unlikely), it should have been resolved with the latest version of the script, so try using that.

If you are still having issues after that, check my latest instructions.

Sorry for the confusion.
