### ISSUE TITLE
Job for openvpn-iptables.service failed because the control process exited with error code.

### ISSUE THREAD

**Issue by jiangliuer326442** [Nyr/openvpn-install#642]
**Job for openvpn-iptables.service failed because the control process exited with error code. See "systemctl status openvpn-iptables.service" and "journalctl -xe" for details.**

i run the command systemctl status openvpn-iptables.service
```
● openvpn-iptables.service
   Loaded: loaded (/etc/systemd/system/openvpn-iptables.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since 四 2019-08-08 21:36:03 CST; 1min 32s ago
 Main PID: 1522 (code=exited, status=2)

8月 08 21:36:02 iZuf699xdglcdywe43sfr7Z systemd[1]: Starting openvpn-iptables.service...
8月 08 21:36:03 iZuf699xdglcdywe43sfr7Z iptables[1522]: iptables v1.4.21: unknown option "--dport"
8月 08 21:36:03 iZuf699xdglcdywe43sfr7Z iptables[1522]: Try `iptables -h' or 'iptables --help' for more information.
8月 08 21:36:03 iZuf699xdglcdywe43sfr7Z systemd[1]: openvpn-iptables.service: main process exited, code=exited, status=2/INVALIDARGUMENT
8月 08 21:36:03 iZuf699xdglcdywe43sfr7Z systemd[1]: Failed to start openvpn-iptables.service.
8月 08 21:36:03 iZuf699xdglcdywe43sfr7Z systemd[1]: Unit openvpn-iptables.service entered failed state.
8月 08 21:36:03 iZuf699xdglcdywe43sfr7Z systemd[1]: openvpn-iptables.service failed.
```

**Comment by jiangliuer326442** [comment]
my mistake

**Comment by rudawem** [comment]
I have the same problem, can you elaborate what was problem or mistake ?
Thanks

**Comment by Nyr** [comment]
@rudawem post the output of `systemctl status openvpn-iptables.service`

Also say what is your operating system and version.

**Comment by rudawem** [comment]
My OS : Ubuntu 20.04 LTS
And I solve the problem, apparently in my OS, iptables path is /usr/sbin/iptables but openvpn-iptables.service was looking at /sbin/iptables with simple soft link problem was solved. 
I use your script many times but this was first time to see this error, maybe dynamic iptables path needed in script. 
BTW thanks for your awesome work!

**Comment by Nyr** [comment]
@rudawem this is a change which I was aware of, but in a default Ubuntu 20.04 install the `/sbin` directory is aliased to `/usr/sbin`:
```
ls -la /sbin
lrwxrwxrwx 1 root root 8 Apr 21 20:18 /sbin -> usr/sbin
```

So it was not problematic.

I'll address this, but may I ask who is your hosting provider? They must be using a custom image.

**Comment by Nyr** [comment]
Fixed, thanks a lot for the report.

For anyone wondering: the issue reported by @rudawem is different from the one in the OP.

**Comment by redness360** [comment]
I have this same issue, log attached. 

-  systemctl status openvpn-iptables.service
* openvpn-iptables.service
   Loaded: loaded (/etc/systemd/system/openvpn-iptables.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2020-10-25 19:07:56 EDT; 3min 10s ago
  Process: 4332 ExecStart=/sbin/iptables -t nat -A POSTROUTING -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to 192.168.50.50 (code=exited, status=2)
 Main PID: 4332 (code=exited, status=2)

Oct 25 19:07:56 OSMC systemd[1]: Starting openvpn-iptables.service...
Oct 25 19:07:56 OSMC iptables[4332]: iptables v1.8.2 (nf_tables): unknown option "--to"
Oct 25 19:07:56 OSMC iptables[4332]: Try `iptables -h' or 'iptables --help' for more information.
Oct 25 19:07:56 OSMC systemd[1]: openvpn-iptables.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 25 19:07:56 OSMC systemd[1]: openvpn-iptables.service: Failed with result 'exit-code'.
Oct 25 19:07:56 OSMC systemd[1]: Failed to start openvpn-iptables.service.

**Comment by hardwebCZ** [comment]
Change OS to ubuntu 18.
