### ISSUE TITLE
--no-check-certificate allows script to be altered in transit

### ISSUE THREAD

**Issue by danry25** [Nyr/openvpn-install#66]
Heads up, any person attacking users of your script can alter or rewrite your script in transit and gain root privileges on any computer they run this script on using the command string you recommend in the README.md. 

Looks like your doing this to shorten the URL? Just use the normal github URL to fix this issue and drop the --no-check-certificate flag.

**Comment by danry25** [comment]
Fixed on pull request #67.

**Comment by Nyr** [comment]
No, I don't do it to shorten the URL. It wouldn't be needed for that anyway since `--no-check-certificate` doesn't have any effect for HTTP requests.

You clearly haven't tested this script as extensively as I had, otherwise you would have noticed how many minimal images lack the ca-certificates package by default. Anyway if you are worried about an adversary with MITM capabilities in a datacenter you shouldn't be running the one liner in the first place.

Oh, and your pull request is still "vulnerable" because:
- The initial redirection is still done over HTTP.
- easy-rsa is downloaded with `--no-check-certificate` too during the installation.

This was already discussed in #24, too.
