### ISSUE TITLE
Possible incompatibilities with Virtuozzo 7?

### ISSUE THREAD

**Issue by andre-paulo98** [Nyr/openvpn-install#664]
Hello, 
I've been having some issues https://github.com/Nyr/openvpn-install/issues/663#issuecomment-541143372 and it seems that there has been some modification before I noticed my little problem.

Could there be something wrong with the script on machines hosted in Virtuozzo 7?

https://forum.lowendspirit.com/viewtopic.php?pid=22569#p22569

**Comment by Nyr** [comment]
Sorry for the late reply.

The script should be compatible, but I can't specifically test it with LES because I don't have a service there. Many users from LES use this installer, so I seriously doubt that there is an issue which I don't know of, because someone else would have already chimed in to report it.

That said, if you want me to check it, I can take a look. Email me the following details:
- Login details for a LES instance cleanly reinstalled with any modern distribution and nothing else
- Range of inbound ports assigned to the VPS
- Any other relevant details

If you email me during the week, it is very possible (but not guaranteed) that I can troubleshoot and get back to you within 12 hours of getting that information.

**Comment by andre-paulo98** [comment]
Got it.
Aparently with OpenVZ7 you have to enable netfilter manually. 
Per https://forum.lowendspirit.com/viewtopic.php?pid=22652#p22652 I just `touch /option.netfilter` and after the server restarted (automatically after some time) it was working again.

Don't really know how you can adapt this to make it work out of the box.

**Comment by Nyr** [comment]
This has been addressed in the referenced commit, thanks a lot for the report.

This is not an OpenVZ 7 problem, this is specific to LowEndSpirit (or any other provider which doesn't do [this](https://docs.openvz.org/openvz_users_guide.webhelp/_using_conntrack_rules_and_nat_tables.html) by default.
