### ISSUE TITLE
limiting bandwidth

### ISSUE THREAD

**Issue by buzz3rs** [Nyr/openvpn-install#665]
Hello Nyr,
I'm sorry for bringing this topic i know its frequent but i have very little knowledge about it and i really need to optimize my server, My country (Iraq) is blocking social media and i'm donating VPN but i keep getting overwhelmed by the net usage so i decided to limit the bandwidth
i used this script : [here](https://serverfault.com/a/702332) but when i enable it i can establish connection but there is not internet (no ping on 8.8.8.8 etc..)
is this script not compatible with your OpenVpn or am i doing something wrong?
Sorry for many questions but it'll mean alot to me

this is my current server.conf (after i edited it for the script) :
`port 1194
proto tcp
dev tun
sndbuf 0
rcvbuf 0
ca ca.crt
cert server.crt
key server.key
dh dh.pem
auth SHA512
tls-auth ta.key 0
topology subnet
server 10.8.0.0 255.255.255.0
ifconfig-pool-persist ipp.txt
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
keepalive 10 120
cipher AES-256-CBC
user nobody
group nogroup
persist-key
persist-tun
status openvpn-status.log
verb 3
crl-verify crl.pem
learn-address /root/limit.sh
script-security 3`

**Comment by Bnosora** [comment]
I also encountered this problem, it seems that it is needed open the packet forwarding function of the sysctl and firewall.（Here is centos7 as an example.Which commands to run based on your current firewall selection. But no matter which one you choose, sysctl command must be running.）

iptables：
#`iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -j MASQUERADE`
//If you have not modified server.conf, keep it 10.8.0.0/24. Otherwise change it to the LAN ip segment in server.conf and denote it as cidr.（such as 10.0.0.0 255.0.0.0→10.0.0.0/8）
#`iptables -vnL -t nat`
#`service iptables save`

firewalld:
#`firewall-cmd --permanent --zone=public --add-masquerade`

sysctl:
#`vim /etc/sysctl.conf`               
 //Edit the sysctl configuration file.

Add this command at the bottom:`net.ipv4.ip_forward = 1`       
//Remember to remove the # in front of this command after adding.（Don't move other #.）

save and exit

#`sysctl -p`
//Enable the modification of sysctl just now.

Finally,reboot.

**Comment by Bnosora** [comment]
This is my way to solve this problem, I hope to be useful to you.

**Comment by buzz3rs** [comment]
> This is my way to solve this problem, I hope to be useful to you.

Hello Bnosora, Thanks for your reply.
I do not have firewall-cmd (firewalld) installed on my server do i have to install it or can i do the same with iptables (or ufw)
Thanks.

**Comment by Nyr** [comment]
@Bnosora's instructions are unrelated to your issue.

You can indeed perform traffic shaping with `tc` which is what the linked script uses, but I have no experience with that to help you further.
