### ISSUE TITLE
Setup with dd-wrt router as client

### ISSUE THREAD

**Issue by hacketaler** [Nyr/openvpn-install#680]
Hi Nyr

I want to use the vpn via my router (dd-wrt), but not able to establish a connection, as I'm not sure what to enter in the config-window and TLS-fields.
dd-wrt does not support an import of the ovpn-file.

Could you please help? (see jpg)

![dd-wrt](https://user-images.githubusercontent.com/45298900/68945564-fab49a80-07b0-11ea-9842-7d3256ade97a.jpg)

![server-file](https://user-images.githubusercontent.com/45298900/68945655-2cc5fc80-07b1-11ea-9360-3773f96c8175.jpg)

**Comment by Nyr** [comment]
To start, the script uses `tls-crypt`, which is different than `tls-auth` but apparently not natively supported by the dd-wrt interface. So at the very least you would need to reconfigure your server to use `tls-auth` instead of `tls-crypt`.

Other than that, you will need to check each option to see if there are more conflicts like this one, just read the client configuration and try to match everything manually.

I have no idea of what kind of OpenVPN build does dd-wrt come with, but you'll have problems if it isn't OpenVPN 2.4 compatible.
