### ISSUE TITLE
The ovpn file can be used on the asusrouter before

### ISSUE THREAD

**Issue by mybrandy** [Nyr/openvpn-install#690]
The ovpn file can be used on the asusrouter before, but it can't run now (can be used in the openvpn software of the mobile phone), it shows that the link fails.（ac88u）
![image](https://user-images.githubusercontent.com/33001317/70231004-7b552e00-1794-11ea-9849-fdc46e73bb79.png)

**Comment by Nyr** [comment]
This is probably due to the switch from `tls-auth` (which was likely supported by your router) to `tls-crypt` (which probably isn't).

You can safely downgrade to `tls-auth` if you know how, or use the latest OpenVPN v2.3 compatible commit which is here: https://github.com/Nyr/openvpn-install/raw/68e48d21b6859c26b04b4713e326d1cd2d40d214/openvpn-install.sh
