### ISSUE TITLE
/etc/services not mapping custom port

### ISSUE THREAD

**Issue by TheConsciousness** [Nyr/openvpn-install#70]
I set my main port to 777, completed the install, rebooted the server, and was unable to connect. Upon further searching through IPTables, I noticed the only entry was tcp/udp openvpn, so I headed over to /etc/services and noticed:

openvpn         1194/tcp
openvpn         1194/udp

Looks like the custom port was not translated over to the services file. Good work though, I'm loving it so far!

**Comment by Nyr** [comment]
I don't think the script nor any user software should change `/etc/services` services at all, correct me if I'm wrong.

I suppose your firewall is using this list as a reference and you did something like `--add-service=openvpn`?

Anyway this should be fixed in the next commit which I'm publishing very soon and will take care of both FirewallD (CentOS) and iptables properly among many other cool things :)

**Comment by TheConsciousness** [comment]
The problem is that I didn't run any commands to change anything. 
Netstat says OpenVPN is listening on 777. IPTables says you opened 1194.
Wheres our issue?

**Comment by Nyr** [comment]
Are you using a firewall?

You should be able to connect right after install at whatever port you selected, except if you are using a firewall.

**Comment by TheConsciousness** [comment]
I ran 'ufw allow 777' and that fixed my issue with not being able to connect, however it is just a workaround.

**Comment by Nyr** [comment]
So yes, you are using a firewall.

As far as I know, ufw is not enabled by default in Ubuntu, so if the user wants to use a custom firewall that's fine, but he needs to add the rules.

My reasoning is: I support firewalls as long as they are enabled by default after a clean OS install. That's why I'm adding FirewallD and iptables support for CentOS. I can't support custom configurations by my users and I assume they know how to configure their firewalls anyway :)
