### ISSUE TITLE
Does not work under DPI situations

### ISSUE THREAD

**Issue by djnotes** [Nyr/openvpn-install#707]
This is a great tool and provides easy installation and user profile for connection. However, vpn setup created by the default configuration can easily be detected by DPI techniques in many ISPs in some countries nowadays. So, the VPN service would not work for more than a couple of hours.       
I wonder if this script is capable of hardening the OpenVPN traffic as well?  Once hardened (by wrapping the traffic in SSL or SSH tunnels) the vpn traffic cannot be detected in ISPs. Are there any options to customize the installation to allow for such hardening or does that have to be done independently on the server?

**Comment by Nyr** [comment]
Unfortunately, this needs to be done by the end user, as this is a cat and mouse game in which I don't have a card to play. Methods to evade filtering change fast, vary from country to country and I can't keep up with all them. Additionally, there is usually very little documentation in English from users in affected countries, which adds to the difficulty for an outsider to help.

The installer will provide you with a clean OpenVPN install and from there it should be relatively easy to adapt for your specific needs.

Another option which you should consider for the purposes of evading censorship would be to use Shadowsocks instead of OpenVPN.
