### ISSUE TITLE
Is there any way to activate IPV6 leak prevention in openvpn

### ISSUE THREAD

**Issue by jacobkuriala** [Nyr/openvpn-install#717]
Is there any way to activate IPV6 leak prevention to OpenVPN server using this script? That would be helpful

**Comment by Nyr** [comment]
Multiple ways:
- Client-side, you can disable IPv6 in the operating system, or let your client take care of it (Viscosity and Eddie provide this functionality for example, I don't know about others).
- The server can push bogus IPv6 routes to the client.
- The server can push a working IPv6 route to the client.

I'd suggest that you address this in your client if you can (most decent clients include options for this) and if your client doesn't implement this functionality, you can either do the second option or disable IPv6 in your client.

Of course the third option is the most desirable and one that I plan to implement into the script as soon as I get some time off from work.

**Comment by baptx** [comment]
If you are using NetworkManager on Linux, you can prevent IPv6 leak by choosing "Link-Local Only" in the IPv6 settings of your Ethernet or WiFi connection.

The best thing would be the openvpn-install.sh script to support IPv6. But an advantage of using only IPv4 on the VPN is that you will know which websites don't support IPv4 since you will get an error "Unable to connect". Another advantage for privacy when using only IPv4 on the VPN is that websites you are visiting will not be able to know the IPv6 address of your server (and eventually associate it with you IPv4 to ban your 2 IP addresses at the same time). If some websites only support IPv6, you could still access them though an SSH tunnel as a SOCKS proxy if your server supports IPv6. For example with dynamic port forwarding: `ssh -fND 1080 <server_ip_address>`.
