### ISSUE TITLE
Adding official support for Fedora

### ISSUE THREAD

**Issue by LyesSaadi** [Nyr/openvpn-install#718]
Hello,

The installer already works fine for Fedora as it is already detected as a redhat installation (through `/etc/redhat-release`). And when using it, it just works fine. No error or tweaks to do, just the script trying to installing epel, failing to do so, but, because all needed packages are already in the official repo, continuing with no issue whatsoever!

So, hey, why not just making it official and having this script officially support Fedora?

¯\\\_(ツ)\_/¯

**Comment by Nyr** [comment]
The only reason why Fedora has not been officially supported is because of its fast release cycle compared to the small number of users running the distro.

So I "support" the distro in the sense that I've even submitted Fedora-specific commits but I don't advertise Fedora support. Just no promises are made. For other distros (Debian, Ubuntu, CentOS), support is very proactive and I always aim to have the script working with their next major releases even before they officially release the stable version.

I just don't want to commit to the same level of support for less popular distributions like Fedora or Amazon Linux and I don't want users to expect it. That of course will not prevent you or anyone else from using my work in Fedora or elsewhere.

That said, Fedora is probably the most popular distribution of those officially not supported. [Global statistics](https://w3techs.com/technologies/details/os-linux) don't look very convincing, but maybe is 
Fedora more popular with small users running their own servers, users which are not included in those statistics?

There are nearly 500 users watching this issue tracker. If you run Fedora and would like official support for your distribution, please reply to this issue and let me know. If a reasonable amount of people reply to this message, I'll reconsider it.

**Comment by LyesSaadi** [comment]
It's ok, I was just asking and I just thought that you weren't aware of the fact that it worked well and that it saved me a whole afternoon of configuration (Thanks for that btw :D)!

Also, I do agree that Global Statistics isn't really a good source as no one would use Fedora for hosting production websites, that would be awful. But for me and other small users as you cited who use it for their private server for hosting things like VPNs and making some tasks remotely or deploying development websites, it surely is more popular than RHEL for example.

I immediately thought of this image released by Matthew Miller, the head of the Fedora Project, in [this conference](https://www.youtube.com/watch?v=DklOE_X2dM8) in 2016 about the ISO download's metrics of Fedora "Flavours", where Servers and Clouds (red (dark & light) and yellow (dark)) do represent a pretty big portion of the cake (~20% of all Fedora ISO's downloads):
![fedora-metrics](https://user-images.githubusercontent.com/33597258/73694503-73543480-46d8-11ea-80bc-bca2bbd98e5c.jpg)
