### ISSUE TITLE
 tls-crypt unwrap error: bad packet ID

### ISSUE THREAD

**Issue by relft** [Nyr/openvpn-install#737]
Hi,

Recently I have installed openvpn using nyr/openvpn-install and works great, easy to isntall and configure on a Debian 10!

I have detected two issues:
1.- on /var/log/syslog when openvpn is connected with for example openvpn client windows (3.1.3 713) we receive this error during vpn session:
Apr  5 19:09:58 vpn openvpn[453]: uservpn/80.58.0.99:62533 tls-crypt unwrap error: bad packet ID (may be a replay): [ #9 / time = (1586103816) Sun Apr  5 18:23:36 2020 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Apr  5 19:09:58 vpn openvpn[453]: uservpn/80.58.0.99:62533 tls-crypt unwrap error: packet replay
Apr  5 19:09:58 vpn openvpn[453]: uservpn/80.58.0.99:62533 TLS Error: tls-crypt unwrapping failed from [AF_INET]80.58.0.99:62533

2.- also detected low performance during winscp copy , max speed 300kb/s when server supports 30mb/s

Any suggestion if both issues are related and how can I solve this?

thanks!

**Comment by Nyr** [comment]
I'd suggest to try the OpenVPN Community client, not the OpenVPN Connect client, which is part of the commercial OpenVPN Connect product. But that is unlikely to help with your issue, just wanted to clarify that.

It is possible that both issues are related, but you should consider that nowadays international transit is congested due to the COVID-19 situation and there is no easy way around that.

Like you, I am a Movistar customer myself and serious congestion in the international transit is happening every day during the evenings and nights. Not much you can do about it, other than setting up a VPN server in a well connected network.

**Comment by relft** [comment]
Hi,

Not really sure that is trsffic congestion, this error was detected on
january....

El dg., 5 d’abr. 2020, 19:57, Nyr <notifications@github.com> va escriure:

**Comment by Nyr** [comment]
Slow performance is never an issue with the script itself.

The connection can be congested, the server CPU busy, your network could have packet loss, etc. Those errors could be an indication that connection quality isn't very good and your low speeds kind of confirm it.

What's the VPN server, a dedi? VPS? Raspberry Pi?
Which is the ISP?
