### ISSUE TITLE
./openvpn-install.sh:row248: openvpn: Command not found

### ISSUE THREAD

**Issue by yourboge** [Nyr/openvpn-install#761]
./openvpn-install.sh:row248: openvpn: Command not found 
success
success
success
success
success
success
Failed to enable unit: Unit file openvpn-server@server.service does not exist.
sed：/etc/openvpn/server/tc.key：No such file or directory

Finished!

**Comment by Nyr** [comment]
Since you don't provide the full installation log, I'll take a guess and say the most likely explanation is that yum/dnf got killed during setup after the system ran out of memory.

If you are using a small VPS, I suggest to use Debian (or Ubuntu) instead, both are more lightweight than CentOS/Fedora.
