### ISSUE TITLE
 Users can still connect to the server after being revoked

### ISSUE THREAD

**Issue by WeiKKJ** [Nyr/openvpn-install#764]
Users can still connect to the server after being revoked
![image](https://user-images.githubusercontent.com/50602973/82820478-d579b500-9ed4-11ea-9064-c56b08b0886e.png)
![image](https://user-images.githubusercontent.com/50602973/82820514-eaeedf00-9ed4-11ea-9c5b-6152a2ee0d68.png)

**Comment by WeiKKJ** [comment]
Execute after systemctl restart openvpn-server@server.service

**Comment by Nyr** [comment]
In (at least) the latest EPEL packages, execute permissions for the "other" group were removed from the /etc/openvpn/server/ directory. Execute permissions in the directory containing the CRL are required so that OpenVPN can stat() and reload the the CRL.

This has now been addressed, thanks for the report.
