### ISSUE TITLE
Archlinux support

### ISSUE THREAD

**Issue by nklmilojevic** [Nyr/openvpn-install#83]
Hi,

Thanks for this script.

Can you maybe modify it to work on Archlinux as well?

Thanks in advance.

**Comment by Nyr** [comment]
Not worth supporting it considering the small user base.

Sorry, but that's it.

**Comment by HLFH** [comment]
Small user base?? @Nyr I'm sure we can support it.

**Comment by Nyr** [comment]
Yes, Arch Linux is very small and nearly an amateur project when compared to Debian and RHEL based distros which clearly dominate the market:
- https://w3techs.com/technologies/details/os-linux/all/all
- https://secure1.securityspace.com/s_survey/data/man.201610/apacheos.html

An independent fork would be a good idea if someone is interested in maintaining that, official support is not going to happen.

**Comment by HLFH** [comment]
Ok. I disagree with these stats. w3techs.com is not so relevant for GNU/Linux stats.
ArchLinux has a pretty [market share here on Reddit](https://brashear.me/blog/2015/08/24/results-of-the-2015-slash-r-slash-linux-distribution-survey/). 
And in the Page Hit Ranking of Distrowatch, [Arch Linux is number 10](https://distrowatch.com/index.php?dataspan=52). 

So, I'll see what I can do (PR?) with the @Angristan fork: https://github.com/Angristan/OpenVPN-install
Have a nice day.

**Comment by Nyr** [comment]
Reddit is not exactly a neutral sample. DistroWatch is useless since the sample is from desktop users.

Look, I don't claim that my referenced stats are tremendously accurate, but they give an overall idea of the situation. It is a fact that Arch has a very small market share in the server market compared to others. Most of the big server hosters don't ever offer Arch as a choice.

I strongly suggest you to stay away from the @Angristan fork: it is buggy, insecure and badly maintained. He's putting users at risk and he either can't or don't want to see it. I'm honestly ashamed that my work has been vandalized like that by someone who claims to have "improved" it.

If you really want to support AND maintain Arch Linux compatibility, create your own fork. If it becomes well maintained, I'll be more than happy to direct Arch users there.

If you still prefer to push a pull request somewhere else where it will be blindly accepted, feel free to do so. The beauty of open source, I guess.

**Comment by Angristan** [comment]
Hey, if you could give more details of what you think I've done wrong, I'll be grateful, thanks.

**Comment by HLFH** [comment]
I'm also interested to get some more details @Nyr. I would be grateful. So, I would know after which repo I'll fork.

**Comment by Nyr** [comment]
@Angristan I think we have already talked about the matter in the past. I am also not that interested in investing time to fix bugs which weren't in my original project. But fair enough, I will try to make some reasonable critique...

- You claim that the default cipher used by my project isn't good enough. I'm no cryptography expert (not even amateur) so I rely on others who know better. Consensus is that the cipher used by my installer is perfectly strong for the current times, while offering good performance. The cipher discussion is thankfully going to be settled for good with the new cipher negotiation in OpenVPN 2.4: nearly everyone will agree that `AES-GCM-256` is a great choice when available.

- You claim to offer AES-GCM but fail to specify that it is only used for the control channel and not the data channel. Not that this is a good idea either given that GCM support is not still widespread enough.


In the readme you advertise AES-GCM but that's then only used for the control channel.


For all of this, I don't really think that you don't have the knoweldge needed to offer a fork claiming that is improved. Or just to offer so others can install it.

**Comment by Nyr** [comment]
(Sorry, did hit the submit button while still writing. Will get back to you soon)

**Comment by Nyr** [comment]
Sorry for the delay, had a busy morning:

@Angristan I think we have already talked about the matter in the past. I am also not that interested in investing time to fix bugs which weren't in my original project. But fair enough, I will try to make some reasonable critique...

- You claim that the default cipher used by my project isn't good enough. I'm no cryptography expert (not even amateur) so I rely on others who know better (and by others I don't mean shiny VPN blogs). Consensus is that the cipher used by my installer is perfectly strong for the current times, while offering good performance. The cipher discussion is thankfully going to be settled for good with the new cipher negotiation in OpenVPN 2.4: nearly everyone will agree that `AES-GCM-256` is a great choice when available.

- You claim to offer AES-GCM but fail to specify that it is only used for the control channel, not the data channel. Not that this is a good idea either given that GCM support is still not widespread enough. Well, at least you somehow warn the user about that.

- The "no logs" feature is simply false. I guess you claim this because you don't even know where are they stored. Anyway if an adversary is able to grab client connection logs (I'm guessing that's what you consider sensitive) from the server, could as well just obtain flow logs from the ISP which are fare more useful and detailed.

- Your reasoning to disable a feature as important as LZO compression for the data channel based on those claims is simply wrong. Those attacks are not viable with OpenVPN like they are (in some specific circumstances) with other software (web browsers).

- One of your advertised improvements is "avoid DNS leak". Sorry, what? When it happens, that's a client side issue so not much you or I can do. Again, I don't think you understand how DNS leaks usually happen. We both implement `block-outside-dns` but I hope you understand that's only to prevent a Windows 10 issue specifically, not a general solution which fixes DNS leaks.

- DNS choice: you use some regional, non-anycast servers which seem to work fine for you in France: ask someone in Asia how's it for them. Also OpenNIC, which I'm sorry but it is ridiculous considering you claim to offer a "hardened" or "more secure" version of my work. Any dumbass can set up a DNS and add it to OpenNIC... or someone who isn't a dumbass at all and has very specific intentions.

- You claim to "support either SNAT or MASQUERADE for forwarding". Again my guess is that you do that because don't understand their differences. I remember that some time ago you opened an issue with me because you didn't understand how to set up the NAT. My guess is that you switched to `MASQUERADE` instead which "worked for you". And you hardcoded `eth0` to it because why not.

Those are just some examples of issues with your modifications, I did just take a look at your readme and looked up the changes in the script. Considering this, I don't think that you have the knowledge needed to offer a fork claiming that is improved. Or more secure. I don't care much about that anyway. The thing which makes me sad is that others are using your work instead of mine assuming that it is better, more secure or that mine is inferior somehow.

I hope that you don't take this criticism as something personal: it's just about your work. I certainly don't like this situation but I'm pretty sure that you had good intentions with that fork. Sadly good intentions do not guarantee good results.

**Comment by HLFH** [comment]
Thank you @Nyr for the heads-up. ¯\_(ツ)_/¯ @Angristan is a [French linuxian blogger](https://angristan.fr/) and frankly, it's rare at his age to use a lot GNU/Linux technologies and to be so curious about them. He likes encryption. We don't pretend to be the best at it. At least, he likes your software, and we are curious about your experience. Because we both like to improve things: at start, there are mistakes, but then, after a lot of tryouts, we are really improving - maybe not a software - but at least our skills.  Thank you again

**Comment by Nyr** [comment]
It's great that other people can experiment, learn and improve, I of course do it too. In fact, this script is only possible thanks to the work of many people way more smarter and knowledgeable than me.

But tens of thousands of users are relying in this piece of my work and as such I take great care in creating something tested, reliable and secure which they can trust. I don't create false expectations about what kind of security or privacy I can offer them, which by the way is extremely common in the VPN scene.

**Comment by Angristan** [comment]
Thanks for the feedback, I'll work on it. 😃 
However I never said my fork was NSA-proof and installing the most secure VPN in the world. You want universality, I want security **(I understand I can do better)**, that's why this fork is here. I'm not a proffesionnal in any domain so I can make mistakes, and I'm sorry about it, but thanks to you, I can improve myself and the script. 
(Saying you're ashamed of my fork is a *bit* exaggerated, it's just a fork, a seperate project, and I don't force any of your users to use mine...)

**Comment by Nyr** [comment]
> You want universality, I want security

That's wrong, I obviously want my script to deploy a secure configuration. And it does. Somehow my choices are not enough for your threat model but I'm not sure what threat model you do have in mind and you haven't explained it anywhere.

> I can improve myself and the script. 

Then start by reading and trying to understand the actual script. You [clearly](https://github.com/Nyr/openvpn-install/issues/162) did [not](https://github.com/Nyr/openvpn-install/issues/138) before deciding to start an "improved" fork. Then, read the goddamn OpenVPN manual which either you haven't read or you haven't understood. And the relevant parts of the iptables manual, too. You can't improve something without understanding how it works.

If you want to get into cryptography discussions, then learn about cryptography too. This is actually 10000x harder than the rest, that's why trusting experts is usually a better idea than trying to make random choices on your own.

> Saying you're ashamed of my fork is a bit exaggerated

That's the truth. Your fork has become somewhat popular and you are carelessly putting people at risk by offering them a buggy, insecure and generally worse version of my work.

> I don't force any of your users to use mine

No, but you advertise an improved version of my work, when it's actually the opposite.

**Comment by PatrickePatate** [comment]
@Nyr just shut up ?

**Comment by Nyr** [comment]
@PatrickePatate you got the unsubscribe button exactly for that.

**Comment by feliwyn** [comment]
« Yes, Arch Linux is very small and nearly an amateur project when compared to Debian and RHEL based distros which clearly dominate the market: »

It's not because « very small » and « amateur » than it's bad.
Look on pornhub's category.

**Comment by Nyr** [comment]
I don't think that a small project is bad for being small.

I am not refusing to support Arch because of a whim. Proper support for a distribution requires many hours of work over the years. I could just modify 10 lines of the code and call it "supported", others do that, but I have higher standards.

It's just a question of resources, of investing that ammount of work into supporting a marginal distribution which has way less than 1% of the server market. I don't even think that any of the cloud providers which I use for testing actually carry Arch images.

**Comment by Nyr** [comment]
@mmendescortes the current version of the script does work in CentOS 7. There was a recent iptables change which has been reversed but only affected iptables, CentOS 7 usually has firewalld.

Try installing in a clean CentOS 7 image, feel free to open a new issue with logs if you have problems, but I don't think that there will be anything wrong with the script.

And please, be respectful to others.

**Comment by mmendescortes** [comment]
Sorry if I was disrespectful...

That was a clean install and I don't use firewalld as I fell more secure with an iptables...

My error was: When trying to start the server, openvpn couldn't create nat rules... Maybe I can create them myself, but even if I do, I don't know if the openvpn would still try to inject it's rules...

I will try with firewalld once, maybe I should give it a try...

**Comment by Nyr** [comment]
@mmendescortes if you were using the version which was reversed, that could be causing issues. Use the latest version currently available and that will work.

If you need further assistance, please open a different issue.

**Comment by Naheel-Azawy** [comment]
Hello @Nyr, looks like I'm a bit late to the party. This discussion is far way longer than I expected.
Anyway, I agree with you that has a much smaller market share. But I actually do use arch for my little vps.
I understand that it's not worth it for you and it's absolutely fine. So I thought I might do it myself.
After taking a quick look over your script, as you mentioned, it looks like it is a matter of changing few lines.

> I am not refusing to support Arch because of a whim. Proper support for a distribution requires many hours of work over the years. I could just modify 10 lines of the code and call it "supported", others do that, but I have higher standards.

I first thought I'll just go ahead and do that. But I'm not an openvpn expert. So, I searched and found this issue.
Can you please talk more about the "higher standards"? I mean, what kind of things should go over to make sure it works well.
I hope it's not a lot, I'm not planning to invest a lot of time on this either.
I also thought of dockerizing it but that would be an overkill I guess.

**Comment by vahidshirvani** [comment]
I have the script running in docker. Please see https://github.com/vahidshirvani/openvpn-install
