### ISSUE TITLE
openvpn-install.sh fails after server upgrade

### ISSUE THREAD

**Issue by sunsetsystems** [Nyr/openvpn-install#860]
I set up openvpn-install on an Ubuntu 18.04 server, then later upgraded the server to Ubuntu 20.04. Everything continued to work until I ran openvpn-install.sh again to set up a new client, and it proceeded to re-run the server install instead, and messed up the existing configuration.

Just something to look at when time permits.

**Comment by Nyr** [comment]
My best guess is that this happened because you ran a newer version of `openvpn-install.sh` which uses a new configuration file structure.

You should keep using the version of the script used for setup during the whole lifetime of your installation. Usually it is not problematic to use a newer version, but there were some breaking changes two years ago to follow the new official OpenVPN guidelines back then.
