### ISSUE TITLE
IP leak on google services

### ISSUE THREAD

**Issue by aligholampour** [Nyr/openvpn-install#873]
when used as client, google detect my real IP and get 403 error.

**Comment by mirsamantajbakhsh** [comment]
I have faced the same issue. Google bans me from accessing some services (Android, Kaggle, ...).
This is a fix around:
_I heard (not tested) that changing the server IP and using [outline](https://getoutline.org/) will solve the problem. However, test for leaks from your browser using some sites such as [browserleaks](https://browserleaks.com/) or [dnsleaktest](https://www.dnsleaktest.com/results.html)._

Thanks @Nyr for the great script. I appreciate if it gets fixed with **openvpn-install**

**Comment by Nyr** [comment]
There is anything to fix within the installer about this.
