### ISSUE TITLE
Please add Rocky Linux distribution support

### ISSUE THREAD

**Issue by reeyon** [Nyr/openvpn-install#895]
Is it possible to add Rocky Linux distribution to the installer script?

**Comment by KG7QIN** [comment]
You can add Rocky support using this patch.  I'll submit a PR on this in a bit.

`--- openvpn-install.sh	2021-08-24 14:02:11.183429687 +0000
+++ openvpn-install-rocky.sh	2021-08-24 14:03:28.287922191 +0000
@@ -38,9 +38,13 @@
 	os="fedora"
 	os_version=$(grep -oE '[0-9]+' /etc/fedora-release | head -1)
 	group_name="nobody"
+elif [[ -e /etc/rocky-release ]]; then
+	os="rocky"
+	os_version=$(grep -oE '[0-9]+' /etc/rocky-release | head -1)
+	group_name="nobody"
 else
 	echo "This installer seems to be running on an unsupported distribution.
-Supported distributions are Ubuntu, Debian, CentOS, and Fedora."
+Supported distributions are Ubuntu, Debian, CentOS, Rocky, and Fedora."
 	exit
 fi
 
@@ -62,6 +66,12 @@
 	exit
 fi
 
+if [[ "$os" == "rocky" && "$os_version" -lt 8 ]]; then
+	echo "RockyOS 8 or higher is required to use this installer.
+This version of RockyOS is too old and unsupported."
+	exit
+fi
+
 # Detect environments where $PATH does not include the sbin directories
 if ! grep -q sbin <<< "$PATH"; then
 	echo '$PATH does not include sbin. Try using "su -" instead of "su".'
@@ -204,7 +214,7 @@
 	echo "OpenVPN installation is ready to begin."
 	# Install a firewall in the rare case where one is not already available
 	if ! systemctl is-active --quiet firewalld.service && ! hash iptables 2>/dev/null; then
-		if [[ "$os" == "centos" || "$os" == "fedora" ]]; then
+		if [[ "$os" -eq "centos" || "$os" -eq "fedora" || "$os" -eq "rocky" ]]; then
 			firewall="firewalld"
 			# We don't want to silently enable firewalld, so we give a subtle warning
 			# If the user continues, firewalld will be installed and enabled during setup
@@ -224,7 +234,7 @@
 	if [[ "$os" = "debian" || "$os" = "ubuntu" ]]; then
 		apt-get update
 		apt-get install -y openvpn openssl ca-certificates $firewall
-	elif [[ "$os" = "centos" ]]; then
+	elif [[ "$os" = "centos" || "$os" == "rocky" ]]; then
 		yum install -y epel-release
 		yum install -y openvpn openssl ca-certificates tar $firewall
 	else
`

**Comment by KG7QIN** [comment]
PR #872 does add support for Rocky Linux, and there are a few changes that were recommended.  Take a look at it if you want to use the script.

Or you could just take this patch file instead and apply it against your openvpn-install.sh to add Rocky Linux support:

```
--- openvpn-install.sh	2021-08-24 14:02:11.183429687 +0000
+++ openvpn-install-rocky.sh	2021-08-24 14:03:28.287922191 +0000
@@ -38,9 +38,13 @@
 	os="fedora"
 	os_version=$(grep -oE '[0-9]+' /etc/fedora-release | head -1)
 	group_name="nobody"
+elif [[ -e /etc/rocky-release ]]; then
+	os="rocky"
+	os_version=$(grep -oE '[0-9]+' /etc/rocky-release | head -1)
+	group_name="nobody"
 else
 	echo "This installer seems to be running on an unsupported distribution.
-Supported distributions are Ubuntu, Debian, CentOS, and Fedora."
+Supported distributions are Ubuntu, Debian, CentOS, Rocky, and Fedora."
 	exit
 fi
 
@@ -62,6 +66,12 @@
 	exit
 fi
 
+if [[ "$os" == "rocky" && "$os_version" -lt 8 ]]; then
+	echo "RockyOS 8 or higher is required to use this installer.
+This version of RockyOS is too old and unsupported."
+	exit
+fi
+
 # Detect environments where $PATH does not include the sbin directories
 if ! grep -q sbin <<< "$PATH"; then
 	echo '$PATH does not include sbin. Try using "su -" instead of "su".'
@@ -204,7 +214,7 @@
 	echo "OpenVPN installation is ready to begin."
 	# Install a firewall in the rare case where one is not already available
 	if ! systemctl is-active --quiet firewalld.service && ! hash iptables 2>/dev/null; then
-		if [[ "$os" == "centos" || "$os" == "fedora" ]]; then
+		if [[ "$os" -eq "centos" || "$os" -eq "fedora" || "$os" -eq "rocky" ]]; then
 			firewall="firewalld"
 			# We don't want to silently enable firewalld, so we give a subtle warning
 			# If the user continues, firewalld will be installed and enabled during setup
@@ -224,7 +234,7 @@
 	if [[ "$os" = "debian" || "$os" = "ubuntu" ]]; then
 		apt-get update
 		apt-get install -y openvpn openssl ca-certificates $firewall
-	elif [[ "$os" = "centos" ]]; then
+	elif [[ "$os" = "centos" || "$os" == "rocky" ]]; then
 		yum install -y epel-release
 		yum install -y openvpn openssl ca-certificates tar $firewall
 	else
```

**Comment by Nyr** [comment]
Alma and Rocky support have been added with the latest commit.
