### ISSUE TITLE
request to upgrade predefined ffdhe group

### ISSUE THREAD

**Issue by clientenq** [Nyr/openvpn-install#897]
This is a request to upgrade the predefined ffdhe group as used in the script.

The current applied Diffie-Hellman group is currently not future proof.
More future proof solutions are probably ffdhe3072 and ffdhe4096.

Since the script seems intended for long time implementations (certificate expiration after nearly 10 years) this would mean many users will use results of the current ffdhe2048 implementation beyond some recommended use.

Current resources indicating moving away from ffdhe2048 to more future proof implementations:

- Internet standards DHE group. Phase out ffdhe2048. https://github.com/internetstandards/dhe_groups/blob/master/README.md
- German Federal office of Information security. Technical Guideline TR-02102-2Cryptographic Mechanisms: Recommendations and Key Lengths. Recommends use of ffdhe2048 not beyond 2021. https://www.bsi.bund.de/SharedDocs/Downloads/EN/BSI/Publications/TechGuidelines/TG02102/BSI-TR-02102-2.pdf

**Comment by Nyr** [comment]
It does not make sense to use 4096 bit DH with the 2048 bit RSA keys which we are currently using.

So if we are upgrading, we are upgrading both. But since 2048 is still a sane default for years to come, I see no reason to change it. I prefer my installer not to be opinionated and use the upstream defaults where it is sensible to do so.
