### ISSUE TITLE
TLS handshake failed

### ISSUE THREAD

**Issue by shetubd** [Nyr/openvpn-install#905]
I install openvpn server in Debain 10. I got TLS handshake failed message. My vpn client is pfsense 2.5.2. 
**vps Server:**
iptables -L

`Chain INPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     udp  --  anywhere             anywhere             udp dpt:openvpn

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTABLISHED
ACCEPT     all  --  10.8.0.0/24          anywhere

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
`
`root@racknerd-b248ab:~# systemctl status openvpn-server@server.service
● openvpn-server@server.service - OpenVPN service for server
   Loaded: loaded (/lib/systemd/system/openvpn-server@.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2021-09-21 05:30:23 EDT; 6min ago
     Docs: man:openvpn(8)
           https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage
           https://community.openvpn.net/openvpn/wiki/HOWTO
 Main PID: 929 (openvpn)
   Status: "Initialization Sequence Completed"
    Tasks: 1 (limit: 1149)
   Memory: 1.5M
   CGroup: /system.slice/system-openvpn\x2dserver.slice/openvpn-server@server.service
           └─929 /usr/sbin/openvpn --status /run/openvpn-server/status-server.log --status-version 2 --suppress-timestamps

Sep 21 05:34:32 racknerd-b248ab openvpn[929]: *********:23261 SIGUSR1[soft,tls-error] received, client-instance resta
Sep 21 05:34:36 racknerd-b248ab openvpn[929]:  *********:23332 TLS: Initial packet from [AF_INET] *********:23332,
Sep 21 05:35:36 racknerd-b248ab openvpn[929]:  *********:23332 TLS Error: TLS key negotiation failed to occur within 6
Sep 21 05:35:36 racknerd-b248ab openvpn[929]:  *********:23332 TLS Error: TLS handshake failed
Sep 21 05:35:36 racknerd-b248ab openvpn[929]:  *********:23332 SIGUSR1[soft,tls-error] received, client-instance resta
Sep 21 05:35:41 racknerd-b248ab openvpn[929]:  *********:23449 TLS: Initial packet from [AF_INET] *********:23449,
Sep 21 05:36:42 racknerd-b248ab openvpn[929]:  *********:23449 TLS Error: TLS key negotiation failed to occur within 6
Sep 21 05:36:42 racknerd-b248ab openvpn[929]: *********:23449 TLS Error: TLS handshake failed
Sep 21 05:36:42 racknerd-b248ab openvpn[929]:  *********:23449 SIGUSR1[soft,tls-error] received, client-instance resta
Sep 21 05:36:46 racknerd-b248ab openvpn[929]: *****:23514 TLS: Initial packet from [AF_INET]*******:23514,`

**Comment by ZDfordream** [comment]
have you solve this problem?

**Comment by SBK79** [comment]
hey i have this problem too

**Comment by SBK79** [comment]
did you find any solution ?!

**Comment by yangtao278080785570121** [comment]
I have solved the problem


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Nyr/openvpn-install"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月16日(星期四) 下午2:54
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [Nyr/openvpn-install] TLS handshake failed (#905)





 
did you find any solution ?!
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SBK79** [comment]
> I have solved the problem
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Nyr/openvpn-install" ***@***.***&gt;; 发送时间:&nbsp;2021年12月16日(星期四) 下午2:54 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;Re: [Nyr/openvpn-install] TLS handshake failed (#905) did you find any solution ?! — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

how did you solved it?!

**Comment by yangtao278080785570121** [comment]
Could you elaborate on your question? I'll judge




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月16日(星期四) 下午3:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Nyr/openvpn-install] TLS handshake failed (#905)





  
I have solved the problem
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Nyr/openvpn-install" @.&gt;; 发送时间:&nbsp;2021年12月16日(星期四) 下午2:54 @.&gt;; @.***&gt;; 主题:&nbsp;Re: [Nyr/openvpn-install] TLS handshake failed (#905) did you find any solution ?! — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
how did you solved it?!
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SBK79** [comment]
here my openvpn server service status 


● openvpn-server@server.service - OpenVPN service for server
   Loaded: loaded (/lib/systemd/system/openvpn-server@.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2021-12-16 11:35:33 +0330; 1min 32s ago
     Docs: man:openvpn(8)
           https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage
           https://community.openvpn.net/openvpn/wiki/HOWTO
 Main PID: 1400 (openvpn)
   Status: "Initialization Sequence Completed"
    Tasks: 1 (limit: 1149)
   Memory: 1.3M
   CGroup: /system.slice/system-openvpn\x2dserver.slice/openvpn-server@server.service
           └─1400 /usr/sbin/openvpn --status /run/openvpn-server/status-server.log --status-version 2 --suppress-timestamps --config server.conf

Dec 16 11:35:33 openvpn[1400]: IFCONFIG POOL: base=10.8.0.2 size=252, ipv6=1
Dec 16 11:35:33 openvpn[1400]: IFCONFIG POOL LIST
Dec 16 11:35:33 openvpn[1400]: MULTI: TCP INIT maxclients=1024 maxevents=1028
Dec 16 11:35:33 openvpn[1400]: Initialization Sequence Completed
Dec 16 11:35:53 openvpn[1400]: TCP connection established with [AF_INET]91.92.185.170:34184
Dec 16 11:36:53 openvpn[1400]: 91.92.185.170:34184 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivi
Dec 16 11:36:53 openvpn[1400]: 91.92.185.170:34184 TLS Error: TLS handshake failed
Dec 16 11:36:53 openvpn[1400]: 91.92.185.170:34184 Fatal TLS error (check_tls_errors_co), restarting
Dec 16 11:36:53 openvpn[1400]: 91.92.185.170:34184 SIGUSR1[soft,tls-error] received, client-instance restarting
Dec 16 11:36:58 openvpn[1400]: TCP connection established with [AF_INET]x.x.x.x:34306




my client log 


Thu Dec 16 11:12:47 2021 Unrecognized option or missing or extra parameter(s) in xiaomi.ovpn:13: block-outside-dns (2.4.7)
Thu Dec 16 11:12:47 2021 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Apr 27 2021
Thu Dec 16 11:12:47 2021 library versions: OpenSSL 1.1.1f  31 Mar 2020, LZO 2.10
Thu Dec 16 11:12:47 2021 Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Thu Dec 16 11:12:47 2021 Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Thu Dec 16 11:12:47 2021 Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Thu Dec 16 11:12:47 2021 Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Thu Dec 16 11:12:47 2021 TCP/UDP: Preserving recently used remote address: [AF_INET]x.x.x.x:1194
Thu Dec 16 11:12:47 2021 Socket Buffers: R=[131072->131072] S=[16384->16384]
Thu Dec 16 11:12:47 2021 Attempting to establish TCP connection with [AF_INET]x.x.x.x:1194 [nonblock]
Thu Dec 16 11:12:48 2021 TCP connection established with [AF_INET]x.x.x.x:1194
Thu Dec 16 11:12:48 2021 TCP_CLIENT link local: (not bound)
Thu Dec 16 11:12:48 2021 TCP_CLIENT link remote: [AF_INET]x.x.x.x:1194
Thu Dec 16 11:13:48 2021 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Thu Dec 16 11:13:48 2021 TLS Error: TLS handshake failed
Thu Dec 16 11:13:48 2021 Fatal TLS error (check_tls_errors_co), restarting
Thu Dec 16 11:13:48 2021 SIGUSR1[soft,tls-error] received, process restarting
Thu Dec 16 11:13:48 2021 Restart pause, 5 second(s)




i have fixed date and checked firewall and added local ip to /etc/openvpn/server.conf

**Comment by SBK79** [comment]
> Could you elaborate on your question? I'll judge
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年12月16日(星期四) 下午3:32 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [Nyr/openvpn-install] TLS handshake failed (#905) I have solved the problem … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Nyr/openvpn-install" @.&gt;; 发送时间:&nbsp;2021年12月16日(星期四) 下午2:54 @.&gt;; @.***&gt;; 主题:&nbsp;Re: [Nyr/openvpn-install] TLS handshake failed (#905) did you find any solution ?! — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. how did you solved it?! — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

here my openvpn server service status 


● openvpn-server@server.service - OpenVPN service for server
   Loaded: loaded (/lib/systemd/system/openvpn-server@.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2021-12-16 11:35:33 +0330; 1min 32s ago
     Docs: man:openvpn(8)
           https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage
           https://community.openvpn.net/openvpn/wiki/HOWTO
 Main PID: 1400 (openvpn)
   Status: "Initialization Sequence Completed"
    Tasks: 1 (limit: 1149)
   Memory: 1.3M
   CGroup: /system.slice/system-openvpn\x2dserver.slice/openvpn-server@server.service
           └─1400 /usr/sbin/openvpn --status /run/openvpn-server/status-server.log --status-version 2 --suppress-timestamps --config server.conf

Dec 16 11:35:33 openvpn[1400]: IFCONFIG POOL: base=10.8.0.2 size=252, ipv6=1
Dec 16 11:35:33 openvpn[1400]: IFCONFIG POOL LIST
Dec 16 11:35:33 openvpn[1400]: MULTI: TCP INIT maxclients=1024 maxevents=1028
Dec 16 11:35:33 openvpn[1400]: Initialization Sequence Completed
Dec 16 11:35:53 openvpn[1400]: TCP connection established with [AF_INET]91.92.185.170:34184
Dec 16 11:36:53 openvpn[1400]: 91.92.185.170:34184 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivi
Dec 16 11:36:53 openvpn[1400]: 91.92.185.170:34184 TLS Error: TLS handshake failed
Dec 16 11:36:53 openvpn[1400]: 91.92.185.170:34184 Fatal TLS error (check_tls_errors_co), restarting
Dec 16 11:36:53 openvpn[1400]: 91.92.185.170:34184 SIGUSR1[soft,tls-error] received, client-instance restarting
Dec 16 11:36:58 openvpn[1400]: TCP connection established with [AF_INET]x.x.x.x:34306




my client log 


Thu Dec 16 11:12:47 2021 Unrecognized option or missing or extra parameter(s) in xiaomi.ovpn:13: block-outside-dns (2.4.7)
Thu Dec 16 11:12:47 2021 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Apr 27 2021
Thu Dec 16 11:12:47 2021 library versions: OpenSSL 1.1.1f  31 Mar 2020, LZO 2.10
Thu Dec 16 11:12:47 2021 Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Thu Dec 16 11:12:47 2021 Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Thu Dec 16 11:12:47 2021 Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Thu Dec 16 11:12:47 2021 Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Thu Dec 16 11:12:47 2021 TCP/UDP: Preserving recently used remote address: [AF_INET]x.x.x.x:1194
Thu Dec 16 11:12:47 2021 Socket Buffers: R=[131072->131072] S=[16384->16384]
Thu Dec 16 11:12:47 2021 Attempting to establish TCP connection with [AF_INET]x.x.x.x:1194 [nonblock]
Thu Dec 16 11:12:48 2021 TCP connection established with [AF_INET]x.x.x.x:1194
Thu Dec 16 11:12:48 2021 TCP_CLIENT link local: (not bound)
Thu Dec 16 11:12:48 2021 TCP_CLIENT link remote: [AF_INET]x.x.x.x:1194
Thu Dec 16 11:13:48 2021 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Thu Dec 16 11:13:48 2021 TLS Error: TLS handshake failed
Thu Dec 16 11:13:48 2021 Fatal TLS error (check_tls_errors_co), restarting
Thu Dec 16 11:13:48 2021 SIGUSR1[soft,tls-error] received, process restarting
Thu Dec 16 11:13:48 2021 Restart pause, 5 second(s)




i have fixed date and checked firewall and added local ip to /etc/openvpn/server.conf

**Comment by yangtao278080785570121** [comment]
Thank you. I got some information I wanted

1. The VPS and PC time are not synchronized

2. The problem I encountered was that the carrier was attacked by ddos, so UDP protocol was banned. I am not sure whether the problem you encountered is the same as mine, please rule it out

3. I don't know what your OS is, can you try to see the system log



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Nyr/openvpn-install"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月16日(星期四) 下午4:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Nyr/openvpn-install] TLS handshake failed (#905)





  
Could you elaborate on your question? I'll judge
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年12月16日(星期四) 下午3:32 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [Nyr/openvpn-install] TLS handshake failed (#905) I have solved the problem … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Nyr/openvpn-install" @.&gt;; 发送时间:&nbsp;2021年12月16日(星期四) 下午2:54 @.&gt;; @.***&gt;; 主题:&nbsp;Re: [Nyr/openvpn-install] TLS handshake failed (#905) did you find any solution ?! — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. how did you solved it?! — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
here my openvpn server service status
 
● ***@***.*** - OpenVPN service for server
 Loaded: loaded ***@***.***; enabled; vendor preset: enabled)
 Active: active (running) since Thu 2021-12-16 11:35:33 +0330; 1min 32s ago
 Docs: man:openvpn(8)
 https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage
 https://community.openvpn.net/openvpn/wiki/HOWTO
 Main PID: 1400 (openvpn)
 Status: "Initialization Sequence Completed"
 Tasks: 1 (limit: 1149)
 Memory: 1.3M
 CGroup: ***@***.***
 └─1400 /usr/sbin/openvpn --status /run/openvpn-server/status-server.log --status-version 2 --suppress-timestamps --config server.conf
 
Dec 16 11:35:33 openvpn[1400]: IFCONFIG POOL: base=10.8.0.2 size=252, ipv6=1
 Dec 16 11:35:33 openvpn[1400]: IFCONFIG POOL LIST
 Dec 16 11:35:33 openvpn[1400]: MULTI: TCP INIT maxclients=1024 maxevents=1028
 Dec 16 11:35:33 openvpn[1400]: Initialization Sequence Completed
 Dec 16 11:35:53 openvpn[1400]: TCP connection established with [AF_INET]91.92.185.170:34184
 Dec 16 11:36:53 openvpn[1400]: 91.92.185.170:34184 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivi
 Dec 16 11:36:53 openvpn[1400]: 91.92.185.170:34184 TLS Error: TLS handshake failed
 Dec 16 11:36:53 openvpn[1400]: 91.92.185.170:34184 Fatal TLS error (check_tls_errors_co), restarting
 Dec 16 11:36:53 openvpn[1400]: 91.92.185.170:34184 SIGUSR1[soft,tls-error] received, client-instance restarting
 Dec 16 11:36:58 openvpn[1400]: TCP connection established with [AF_INET]x.x.x.x:34306
 
my client log
 
Thu Dec 16 11:12:47 2021 Unrecognized option or missing or extra parameter(s) in xiaomi.ovpn:13: block-outside-dns (2.4.7)
 Thu Dec 16 11:12:47 2021 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Apr 27 2021
 Thu Dec 16 11:12:47 2021 library versions: OpenSSL 1.1.1f  31 Mar 2020, LZO 2.10
 Thu Dec 16 11:12:47 2021 Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
 Thu Dec 16 11:12:47 2021 Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
 Thu Dec 16 11:12:47 2021 Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
 Thu Dec 16 11:12:47 2021 Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
 Thu Dec 16 11:12:47 2021 TCP/UDP: Preserving recently used remote address: [AF_INET]x.x.x.x:1194
 Thu Dec 16 11:12:47 2021 Socket Buffers: R=[131072-&gt;131072] S=[16384-&gt;16384]
 Thu Dec 16 11:12:47 2021 Attempting to establish TCP connection with [AF_INET]x.x.x.x:1194 [nonblock]
 Thu Dec 16 11:12:48 2021 TCP connection established with [AF_INET]x.x.x.x:1194
 Thu Dec 16 11:12:48 2021 TCP_CLIENT link local: (not bound)
 Thu Dec 16 11:12:48 2021 TCP_CLIENT link remote: [AF_INET]x.x.x.x:1194
 Thu Dec 16 11:13:48 2021 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
 Thu Dec 16 11:13:48 2021 TLS Error: TLS handshake failed
 Thu Dec 16 11:13:48 2021 Fatal TLS error (check_tls_errors_co), restarting
 Thu Dec 16 11:13:48 2021 SIGUSR1[soft,tls-error] received, process restarting
 Thu Dec 16 11:13:48 2021 Restart pause, 5 second(s)
 
i have fixed date and checked firewall and added local ip to /etc/openvpn/server.conf
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Nyr** [comment]
Generally speaking, this error message indicates a connectivity issue, not a problem with this installer.

For those in China, it is usually blocking at the network level and you need to use [other tools](https://www.v2fly.org/).
