### ISSUE TITLE
Insecure cipher suites

### ISSUE THREAD

**Issue by lmorg** [Nyr/openvpn-install#94]
The default array of cipher suites includes a number of cipher with known vulnerabilities and a few other ciphers which are now computationally cheap to crack (given modern computing power).

OpenVPN's hardening wiki: https://community.openvpn.net/openvpn/wiki/Hardening

### Background (conversation continued from: https://github.com/Nyr/openvpn-install/pull/90)

> No, no, no and no. I'm not going to force my users to upgrade/break their system, this scripts installs OpenVPN and that's it. I'm definitively not forcing an upgrade on anyone because that's not the expected outcome of an OpenVPN installer.

You also install `iptables`, `openssl`, `wget` and another 3rd party tool via `wget` (the latter of which you've only just secured thanks to our discussions). You also do an `apt-get update` prior to installing the aforementioned, which means any dependant software will also need to be updated regardless of running an `$(which apt-get yum) upgrade`. So you are updating and modifying the users' server in all sorts of ways which you're not documenting anywhere.

Since your script isn't just an OpenVPN installer but more an "OpenVPN for dummies" (so to speak) I think it makes a lot of sense to also handle the suggestions myself and others have made. But if you feel that's a step too far then that's fine. I can relate to that. However you then still need to be clear that this is doing more than just installing OpenVPN and that you make no effort to secure the install. eg you make no mention of anywhere that you're installing and editing iptables rules and the scope for breaking things there is much greater than a simple `yum update`. And you make no mention that you're supporting insecure ciphers. The README would lead many to assume that this is a secure out-of-the-box solution which it seems is not the case judging from the issues you've closed and your reasons behind those decisions.

I'm genuinely not trying to be rude. I can see this is a popular project so I'm only offering you my experience so this project can improve and nobody gets any unexpected, nasty, surprises.

> You've only listed one "vulnerability": a one-liner which is completely optional. Open a new issue if you find any reasonable vulnerability within openvpn-install.sh and I'll make sure to address it. Until then, don't waste more of my time.

I listed quite a few vulnerabilities actually. But I don't really want to get into an argument. I'm just offering up friendly suggestions for hardening your installer. :+1:

**Comment by Nyr** [comment]
I'll quote myself again because you seem to have big problems understanding English:

> Unfortunately, update in yum = upgrade in apt-get

See? I mention `yum update`, not `yum upgrade`. And my statement is right.

> You also install iptables as well as other 3rd party tools via wget

Because both `iptables` (which is likely already present) and `easy-rsa` (which is not a package, just a third party script) are NEEDED for the script to do its work. I obviously install REQUIRED dependencies because else the script couldn't work.

> You're using the default array of cipher suites which include a number of cipher with known vulnerabilities and a few other ciphers which are now computationally cheap to crack (given modern computing power).

You are right that OpenSSL supports a lot of the "less secure" ciphers and they could theoretically be used for the control channel, but downgrading during negotiation is nearly impossible and by default weaker cyphers are the latest in order of preference so stronger ones are used.

I'll also quote what's the position from the OpenVPN guys in this matter:
> --tls-cipher really is an expert feature. [...] unlike browsers, OpenVPN does not perform a 'downgrade dance', making it a lot saner to rely on the SSL libary's own version/cipher downgrade protection.

Anyway, setting specific TLS cyphers is a bad idea which could cause more trouble than benefit. It would be way better instead to forbid weak ciphers instead. Please also remember that this is a default/barebones installer and those are the defaults suggested by the developers. I try to leave personal preference (from both me and you) away from the script as much as possible.
